-- Minimal production-shaped schema for PostgreSQL smoke-testing Bizim Skor League migrations.
-- Runs only in ephemeral GitHub Actions PostgreSQL; never against production.

DO $$ BEGIN
  CREATE ROLE anon NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE ROLE authenticated NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

create table public.players (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  is_active boolean default true
);

create table public.fixtures (
  id bigint primary key,
  season text not null,
  week integer not null,
  kickoff timestamptz not null
);
create table public.predictions (
  id bigint generated by default as identity primary key,
  player_name text not null,
  fixture_id bigint not null,
  week integer,
  home_score integer,
  away_score integer,
  created_at timestamptz default now()
);
create table public.results (
  fixture_id bigint primary key,
  home_score integer,
  away_score integer
);

create table public.champions_league_fixtures (
  id bigint primary key,
  season text not null,
  week integer not null,
  kickoff timestamptz not null
);
create table public.champions_league_predictions (
  player_name text not null,
  fixture_id bigint not null,
  home_score smallint,
  away_score smallint
);
create table public.champions_league_results (
  fixture_id bigint primary key,
  home_score smallint,
  away_score smallint
);

create table public.nations_league_fixtures (
  id bigint primary key,
  season text not null,
  week integer not null,
  kickoff timestamptz not null
);
create table public.nations_league_predictions (
  player_name text not null,
  fixture_id bigint not null,
  home_score smallint,
  away_score smallint
);
create table public.nations_league_results (
  fixture_id bigint primary key,
  home_score smallint,
  away_score smallint
);

create table public.player_invites (
  id bigint generated by default as identity primary key,
  inviter_name text not null,
  invited_name text not null,
  created_at timestamptz default now()
);

create or replace function public.friend_session_player(p_token text)
returns text language sql stable as $$ select null::text $$;

create or replace function public.champions_match_points(
  p_fixture_id bigint,p_home smallint,p_away smallint,r_home smallint,r_away smallint
) returns integer language sql immutable as $$ select 0 $$;

create or replace function public.nations_match_points(
  p_fixture_id bigint,p_home smallint,p_away smallint,r_home smallint,r_away smallint
) returns integer language sql immutable as $$ select 0 $$;

-- pg_cron API stub. Production uses the real pg_cron extension; this only validates migration SQL dependencies.
create schema cron;
create table cron.job (
  jobid bigint generated by default as identity primary key,
  jobname text unique
);
create or replace function cron.schedule(p_jobname text,p_schedule text,p_command text)
returns bigint language plpgsql as $$
declare v_id bigint;
begin
  insert into cron.job(jobname) values(p_jobname)
  on conflict(jobname) do update set jobname=excluded.jobname
  returning jobid into v_id;
  return v_id;
end;
$$;
create or replace function cron.unschedule(p_jobid bigint)
returns boolean language plpgsql as $$
begin
  delete from cron.job where jobid=p_jobid;
  return true;
end;
$$;
