const assert=require('assert');
const feature=require('./admin-supported-team-stats.js');
const selected=Array.from({length:8},(_,i)=>({player_name:`Oyuncu${i+1}`,supported_team:i%2?'fenerbahce':'galatasaray'}));
const unselected=Array.from({length:7},(_,i)=>({player_name:`Secmeyen${i+1}`,supported_team:null}));
const html=feature.render({selected_count:selected.length,unselected_count:unselected.length,selected,unselected});
assert(html.includes('Takım Seçen'));
assert(html.includes('Takım Seçmeyen'));
assert(html.includes('data-admin-stats-toggle'));
assert(html.includes('Tümünü Göster (8)'));
assert(html.includes('Tümünü Göster (7)'));
assert(html.includes('bs-admin-stats-extra'));
assert(html.includes('data-admin-supported-list="selected"'));
assert(html.includes('data-admin-supported-list="unselected"'));
console.log('admin supported team stats ok');
