const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('admin-inactive-21d.js','utf8');
assert(src.includes('21 Gündür Oyuna Girmeyen'));
assert(src.includes('Aktif Oyuncu'));
assert(src.includes('Toplam Oyuncu'));
assert(src.includes('Aktif Katılım'));
assert(src.includes('total_registered'));
assert(src.includes('inactive_21d'));
assert(src.includes('data-admin-stats-toggle'));
assert(src.includes('bs-admin-stats-extra'));
assert(src.includes('get_admin_statistics_dashboard'));
assert(!src.includes('MutationObserver'));
console.log('admin inactive 21d contract ok');
