const fs=require('fs');
const assert=require('assert');
const loader=fs.readFileSync('ui-integration-loader.js','utf8');
const ui=fs.existsSync('arena-season1-rules-ui.js')?fs.readFileSync('arena-season1-rules-ui.js','utf8'):'';
assert(loader.includes("'arena-season1-rules-ui.js'"),'Arena sezon 1 kural arayüzü yüklenmeli');
assert(ui.includes('4 Süper Lig haftası'),'Arena sezonu 4 Süper Lig haftası olarak açıklanmalı');
assert(ui.includes('en az 2'),'Minimum 2 Süper Lig haftası katılım şartı açıklanmalı');
assert(ui.includes('kayıt olmadan önce'),'Yeni oyuncunun kayıt öncesi turlarının puanı düşürmeyeceği açıklanmalı');
assert(ui.includes('0 puan'),'Erişilebilir ama kaçırılan turun sıfır puan sayılacağı açıklanmalı');
assert(ui.includes('ortalamaya katılır, tur sayısına katılmaz'),'Şampiyonlar Ligi ve Uluslar Ligi katkısı doğru açıklanmalı');
assert(!ui.includes('7. Süper Lig haftasında hiç tahmin yapmayan'),'Eski 7. hafta özel düşme kuralı kaldırılmalı');
assert(ui.includes('rounds_needed'),'Oyuncuya canlı minimum katılım durumu gösterilmeli');
console.log('Arena fair-access rules UI contract ok');
