const assert=require('assert');
const loader=require('./ui-integration-loader.js');
const order=loader.scriptOrder();
assert.ok(order.includes('brand-assets.js'),'brand assets module must load');
assert.ok(order.includes('brand-visual-ui.js'),'brand visual decorator must load');
assert.ok(order.indexOf('brand-assets.js')<order.indexOf('header-ui.js'),'brand assets must load before header UI');
assert.ok(order.indexOf('header-ui.js')<order.indexOf('brand-visual-ui.js'),'header UI must exist before visual decorator');
assert.ok(order.indexOf('brand-visual-ui.js')<order.indexOf('ranking-movement.js'),'visual decorator must mount before non-critical feature modules');
assert.ok(order.indexOf('brand-visual-ui.js')<order.indexOf('home-dashboard-ui.js'),'visual decorator must observe dashboard as it is created');
assert.ok(order.indexOf('brand-visual-ui.js')<order.indexOf('fixture-ui.js'),'visual decorator must observe fixtures as they are created');
console.log('brand visual loader ok');
