(function(root,factory){
  const api=factory(root);
  if(typeof module==='object'&&module.exports)module.exports=api;
  else{root.BizimSkorHeaderUI=api;api.mount();}
})(typeof globalThis!=='undefined'?globalThis:this,function(root){
  const esc=value=>String(value??'').replace(/[&<>'\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[char]));
  function headerAccountState(name){const clean=String(name||'').trim();return clean?{loggedIn:true,name:clean,action:'Çıkış Yap'}:{loggedIn:false,name:'',action:'Giriş Yap'}}
  function buildHeaderMarkup(name,pushEnabled=false){const state=headerAccountState(name);return `<div class="bs-header-brand"><img class="bs-header-logo" src="bizim-skor-logo-v2.png" alt="Bizim Skor — Sezonluk Arkadaş Ligi"></div><div class="bs-header-account">${state.loggedIn?`<span class="bs-header-user">👤 ${esc(state.name)}</span><div class="bs-header-actions"><button id="bsHeaderUpdate" type="button">Bilgilerimi Güncelle</button><button id="bsHeaderPush" type="button">${pushEnabled?'🔕 Bildirimleri Kapat':'🔔 Bildirimleri Aç'}</button><button id="bsHeaderAccountAction" type="button">Çıkış Yap</button></div>`:`<button id="bsHeaderAccountAction" type="button">Giriş Yap</button>`}</div>`}
  function homeActionMarkup(){return '<button id="bsHeaderHomeAction" class="bs-header-home" type="button" data-tab="home">🏠 Ana Sayfa</button>'}
  function headerStyleMarkup(){return '<style id="bsHeaderStyles">.h.bs-modern-header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:10px 12px;text-align:left;min-height:92px}.bs-header-brand{min-width:0;flex:1}.bs-header-logo{display:block;width:min(285px,100%);height:auto;max-height:118px;object-fit:contain;object-position:left center}.bs-header-account{display:flex;align-items:center;justify-content:flex-end;gap:7px;flex-wrap:wrap}.bs-header-actions{display:flex;justify-content:flex-end;gap:5px;flex-wrap:wrap}.bs-header-user{font-size:13px;font-weight:900;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.bs-header-account button,.bs-header-home{background:#fff;color:#0f172a;border:1px solid #cbd5e1;padding:8px 9px;border-radius:10px;font-size:11px;font-weight:800}.bs-header-home{display:block;width:100%;margin:0 0 12px;font-size:14px;font-weight:900;text-align:left}.tabs.bs-nav-ready>.tab[data-tab="home"]{display:none!important}.bs-header-account button:active,.bs-header-home:active{transform:translateY(1px)}#knownPlayer.bs-account-details-hidden{display:none!important}@media(max-width:430px){.h.bs-modern-header{align-items:center;min-height:104px}.bs-header-logo{width:min(205px,100%);max-height:88px}.bs-header-account{max-width:190px}.bs-header-user{max-width:170px;font-size:12px}.bs-header-actions{gap:4px}.bs-header-account button{padding:7px 6px;font-size:9px}}</style>'}
  function activePredictionInputs(section){if(!section||section.classList?.contains?.('hide'))return[];return Array.from(section.querySelectorAll?.('input.s:not(:disabled), .champions-match input:not(:disabled)')||[])}
  function hasUnsavedPredictionChanges(doc){if(!doc)return false;const inputs=[...activePredictionInputs(doc.getElementById('pred')),...activePredictionInputs(doc.getElementById('championsPred'))];return inputs.some(input=>String(input.value??'')!==String(input.defaultValue??''))}
  function navigateHome(doc,confirmFn){if(!doc)return false;if(hasUnsavedPredictionChanges(doc)){const ask=typeof confirmFn==='function'?confirmFn:root?.confirm?.bind(root);if(ask&&!ask('Kaydedilmemiş tahmin değişikliklerin var. Ana Sayfa’ya dönersen bu değişiklikler kaybolacak. Devam etmek istiyor musun?'))return false}doc.querySelector('[data-tab="home"]:not(#bsHeaderHomeAction)')?.click();return true}
  function ensureStyles(){if(typeof document==='undefined'||document.getElementById('bsHeaderStyles'))return;document.head.insertAdjacentHTML('beforeend',headerStyleMarkup())}
  function ensureHomeAction(header){if(typeof document==='undefined'||document.getElementById('bsHeaderHomeAction'))return;header.insertAdjacentHTML('afterend',homeActionMarkup());document.getElementById('bsHeaderHomeAction')?.addEventListener('click',event=>{event.preventDefault();navigateHome(document)})}
  function openUpdate(){const old=document.getElementById('updatePlayer');if(old){old.click();return}const known=document.getElementById('knownPlayer');known?.classList.remove('bs-account-details-hidden');known?.scrollIntoView?.({behavior:'smooth',block:'center'})}
  function hideOldDetails(loggedIn){const known=document.getElementById('knownPlayer');if(known)known.classList.toggle('bs-account-details-hidden',!!loggedIn)}
  function refresh(){if(typeof document==='undefined')return;const header=document.querySelector('.h');if(!header)return;const name=root?.localStorage?.getItem('bizimSkorName')||'',pushEnabled=root?.localStorage?.getItem('bizimSkorPushEnabledV1')==='1';header.classList.add('bs-modern-header');header.innerHTML=buildHeaderMarkup(name,pushEnabled);ensureHomeAction(header);const state=headerAccountState(name);hideOldDetails(state.loggedIn);document.getElementById('bsHeaderUpdate')?.addEventListener('click',openUpdate);document.getElementById('bsHeaderPush')?.addEventListener('click',async()=>{try{await root.BizimSkorPush?.toggle?.();setTimeout(refresh,50)}catch(e){alert(e.message||String(e))}});const action=document.getElementById('bsHeaderAccountAction');if(!action)return;action.addEventListener('click',()=>{if(headerAccountState(root?.localStorage?.getItem('bizimSkorName')).loggedIn){document.getElementById('logoutPlayer')?.click();setTimeout(refresh,80);return}navigateHome(document,()=>true);document.getElementById('showLogin')?.click();document.getElementById('newPlayer')?.scrollIntoView?.({behavior:'smooth',block:'center'});document.getElementById('loginName')?.focus?.()})}
  function mount(){if(typeof document==='undefined')return;ensureStyles();refresh();const targets=[document.getElementById('knownPlayer'),document.getElementById('newPlayer'),document.getElementById('knownName')].filter(Boolean);if(typeof MutationObserver==='function'&&targets.length){const observer=new MutationObserver(()=>setTimeout(refresh,0));targets.forEach(target=>observer.observe(target,{attributes:true,childList:true,subtree:true,attributeFilter:['class']}))}root?.addEventListener?.('focus',refresh)}
  return Object.freeze({headerAccountState,buildHeaderMarkup,homeActionMarkup,headerStyleMarkup,hasUnsavedPredictionChanges,navigateHome,refresh,mount});
});
