const assert=require('assert');
const ui=require('./header-ui.js');
assert.deepStrictEqual(ui.headerAccountState('Erdal'),{loggedIn:true,name:'Erdal',action:'Çıkış Yap'});
assert.deepStrictEqual(ui.headerAccountState(''),{loggedIn:false,name:'',action:'Giriş Yap'});
assert.strictEqual(typeof ui.buildHeaderMarkup,'function');
const logged=ui.buildHeaderMarkup('Erdal',false);
assert.ok(logged.includes('bizim-skor-logo-v2.png'));
assert.ok(logged.includes('Bilgilerimi Güncelle'));
assert.ok(logged.includes('Bildirimleri Aç'));
assert.ok(logged.includes('Çıkış Yap'));
assert.ok(ui.buildHeaderMarkup('Erdal',true).includes('Bildirimleri Kapat'));
assert.ok(ui.buildHeaderMarkup('').includes('Giriş Yap'));
assert.strictEqual(typeof ui.homeActionMarkup,'function');
assert.ok(ui.homeActionMarkup().includes('Ana Sayfa'));
console.log('header-ui ok');
