const assert=require('assert');
const ui=require('./header-ui.js');
assert.deepStrictEqual(ui.headerAccountState('Erdal'),{loggedIn:true,name:'Erdal',action:'Çıkış Yap'});
assert.deepStrictEqual(ui.headerAccountState(''),{loggedIn:false,name:'',action:'Giriş Yap'});
assert.strictEqual(typeof ui.buildHeaderMarkup,'function');
assert.ok(ui.buildHeaderMarkup('Erdal').includes('bizim-skor-logo-v2.png'));
assert.ok(ui.buildHeaderMarkup('Erdal').includes('Çıkış Yap'));
assert.ok(ui.buildHeaderMarkup('').includes('Giriş Yap'));
assert.strictEqual(typeof ui.homeActionMarkup,'function');
assert.ok(ui.homeActionMarkup().includes('Ana Sayfa'));
assert.ok(ui.homeActionMarkup().includes('data-tab="home"'));
console.log('header-ui ok');
