const fs=require('fs');
const assert=require('assert');
const supported=fs.readFileSync('supported-team-ui.js','utf8');
const patch=fs.readFileSync('museum-team-logo-fix.js','utf8');
const loader=fs.readFileSync('ui-integration-loader.js','utf8');
assert(supported.includes('refresh,contextMap')||supported.includes('contextMap,refresh'),'supported-team-ui refresh API dışa açılmalı');
assert(patch.includes('BizimSkorSupportedTeam')&&patch.includes('.refresh'),'müze logo düzeltmesi supported-team refresh çağırmalı');
assert(patch.includes('bsPlayerMuseumModal'),'müze modalı hedeflenmeli');
assert(loader.includes("'museum-team-logo-fix.js'"),'müze takım logosu düzeltmesi loader üzerinden yüklenmeli');
console.log('museum supported-team logo integration ok');
