(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BizimSkorPlayerProfile=api;api.mount();}})(typeof globalThis!=='undefined'?globalThis:this,function(root){
const BOARD_IDS=new Set(['weeklyRankingBoard','sezuBoard','generalBoard','championsRankingBoard','championsWeeklyRankingBoard','nationsRankingBoard','nationsWeeklyRankingBoard','friendLeagueRanking']);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const outcome=(home,away)=>+home>+away?'1':+home<+away?'2':'X';
function matchSymbol(row){if(row.predicted_home==null||row.predicted_away==null||row.real_home==null||row.real_away==null)return'';if(+row.predicted_home===+row.real_home&&+row.predicted_away===+row.real_away)return'🎯';return outcome(row.predicted_home,row.predicted_away)===outcome(row.real_home,row.real_away)?'⚽':''}
function playerButton(name,week,kind){const weekAttr=Number.isInteger(+week)&&+week>0?` data-profile-week="${+week}"`:'';const kindAttr=kind?` data-profile-kind="${esc(kind)}"`:'';return `<button type="button" class="bs-player-profile-link" data-player-name="${esc(name)}"${weekAttr}${kindAttr} aria-label="${esc(name)} oyuncu profilini aç">${esc(name)}</button>`}
function profileRpcArgs(token,name,week){const args={p_token:token,p_player_name:name};if(Number.isInteger(+week)&&+week>0)args.p_week=+week;return args}
function championsProfileRpcArgs(token,name,week){return{p_token:token,p_player_name:name,p_season:'2026/27',p_week:Number.isInteger(+week)&&+week>0?+week:1}}
function nationsProfileRpcArgs(token,name,week){return{p_token:token,p_player_name:name,p_season:'2026/27',p_week:Number.isInteger(+week)&&+week>0?+week:1}}
function profileRequest(token,name,week,kind){if(kind==='champions')return{rpc:'get_champions_league_player_profile_v2',args:championsProfileRpcArgs(token,name,week)};if(kind==='nations')return{rpc:'get_nations_league_player_profile_v2',args:nationsProfileRpcArgs(token,name,week)};return{rpc:'get_player_public_profile_v2',args:profileRpcArgs(token,name,week)}}
function buildModel(rows){const first=(rows||[])[0]||{},specialKind=String(first.special_kind||''),championsWeek=specialKind==='champions_week',nationsWeek=specialKind==='nations_week',special=specialKind==='champions'||championsWeek||nationsWeek,week=+first.week||null;return{kind:nationsWeek?'nations':championsWeek?'champions':'super',name:first.player_name||'',week,weekLabel:nationsWeek?`UEFA Uluslar Ligi ${week||'—'}. Hafta Sıralaması`:championsWeek?`Şampiyonlar Ligi ${week||'—'}. Hafta Sıralaması`:`${week||'—'}. Hafta Sıralaması`,weekRank:+first.week_rank||null,weekPoints:+first.week_points||0,weekExact:+first.week_exact||0,weekCorrect:+first.week_correct||0,generalRank:+first.general_rank||null,participantCount:+first.participant_count||0,specialLabel:nationsWeek?'UEFA Uluslar Ligi Genel Sıralaması':championsWeek?'Şampiyonlar Ligi Genel Sıralaması':special?'Şampiyonlar Ligi Sıralaması':'Sezu Sıralaması',specialRank:+(nationsWeek?first.champions_rank:special?first.champions_rank:first.sezu_rank)||null,matches:(rows||[]).filter(row=>row.fixture_id!=null).map(row=>({...row,prediction:row.predicted_home==null||row.predicted_away==null?'*-*':`${row.predicted_home}-${row.predicted_away}${row.robot_applied?' 🤖':''}`,result:row.real_home==null||row.real_away==null?'—':`${row.real_home}-${row.real_away}`,symbol:matchSymbol(row)}))}}
const rank=value=>value?`${value}.`:'—';
function profileStatsMarkup(model){if(model.kind==='champions'||model.kind==='nations')return `<div class="bs-profile-stats"><div><span>${esc(model.weekLabel)}</span><b>${rank(model.weekRank)}</b><small>${model.weekPoints} puan</small></div><div><span>${esc(model.specialLabel)}</span><b>${rank(model.specialRank)}</b></div><div><span>Katılan</span><b>${model.participantCount||'—'}</b></div></div>`;return `<div class="bs-profile-stats"><div><span>${model.week||'—'}. Hafta Sıralaması</span><b>${rank(model.weekRank)}</b><small>${model.weekPoints} puan</small></div><div><span>${esc(model.specialLabel)}</span><b>${rank(model.specialRank)}</b></div><div><span>Süper Lig Genel Sıralaması</span><b>${rank(model.generalRank)}</b></div></div>`}
function profileTitle(model){return model.kind==='nations'?'UEFA ULUSLAR LİGİ PROFİLİ':model.kind==='champions'?'ŞAMPİYONLAR LİGİ PROFİLİ':'OYUNCU PROFİLİ'}
function profileMarkup(model){const matches=model.matches.map(row=>`<div class="bs-profile-match"><div><span>${esc(row.home_team)}</span><b>${esc(row.result)}</b><span>${esc(row.away_team)}</span></div><p>Tahmini: <strong>${esc(row.prediction)}</strong>${row.symbol?` <span class="bs-profile-symbol">${row.symbol}${row.match_points?` +${row.match_points}`:''}</span>`:''}</p></div>`).join('')||'<p class="small">Bu hafta için tahmin bulunamadı.</p>';return `<div class="bs-profile-head"><div><span>${profileTitle(model)}</span><h2>${esc(model.name)}</h2></div><button type="button" data-player-profile-close aria-label="Profili kapat">×</button></div>${profileStatsMarkup(model)}<div class="bs-profile-form"><span>Bu hafta</span><b>${model.weekExact} 🎯 • ${model.weekCorrect} ⚽</b></div><p class="bs-profile-note">Başlamamış maçların rakip tahminleri gizlidir.</p><div class="bs-profile-matches">${matches}</div>`}
function ensureShell(doc=document){let shell=doc.getElementById('bsPlayerProfileModal');if(shell)return shell;shell=doc.createElement('div');shell.id='bsPlayerProfileModal';shell.className='bs-profile-modal hide';shell.innerHTML='<div class="bs-profile-backdrop" data-player-profile-close></div><div class="bs-profile-card" role="dialog" aria-modal="true" aria-live="polite"><p class="small">Oyuncu profili yükleniyor…</p></div>';doc.body.appendChild(shell);if(!doc.getElementById('bsPlayerProfileStyles'))doc.head.insertAdjacentHTML('beforeend','<style id="bsPlayerProfileStyles">.bs-player-profile-link{appearance:none;border:0;background:transparent;color:#1454a3;font:inherit;font-weight:800;padding:6px 2px;text-decoration:underline;text-decoration-style:dotted;text-underline-offset:3px;cursor:pointer}.bs-profile-modal{position:fixed;inset:0;z-index:10020;display:flex;align-items:flex-end;justify-content:center}.bs-profile-modal.hide{display:none}.bs-profile-backdrop{position:absolute;inset:0;background:rgba(3,12,28,.64);backdrop-filter:blur(3px)}.bs-profile-card{position:relative;width:min(100%,560px);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:24px 24px 0 0;padding:20px;color:#0f172a;box-shadow:0 -16px 50px rgba(0,0,0,.25)}.bs-profile-head{display:flex;align-items:flex-start;justify-content:space-between}.bs-profile-head span{font-size:11px;letter-spacing:2px;color:#64748b;font-weight:900}.bs-profile-head h2{margin:4px 0 14px}.bs-profile-head button{border:0;background:#e2e8f0;border-radius:50%;width:38px;height:38px;font-size:26px}.bs-profile-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.bs-profile-stats>div{padding:12px 6px;border:1px solid #dbe3ee;border-radius:14px;text-align:center;background:#fff}.bs-profile-stats span,.bs-profile-stats small{display:block;font-size:10px;color:#64748b}.bs-profile-stats b{display:block;font-size:21px;margin:5px 0}.bs-profile-form{display:flex;justify-content:space-between;margin:12px 0 4px;padding:12px 14px;border-radius:14px;background:#eaf2ff}.bs-profile-note{font-size:11px;color:#64748b}.bs-profile-match{padding:12px 0;border-top:1px solid #e2e8f0}.bs-profile-match>div{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:8px}.bs-profile-match>div span:last-child{text-align:right}.bs-profile-match p{margin:6px 0 0;color:#475569}.bs-profile-symbol{float:right;font-weight:900}@media(min-width:620px){.bs-profile-modal{align-items:center}.bs-profile-card{border-radius:24px}}</style>');return shell}
function decorateBoard(board){const champions=board.id==='championsRankingBoard'||board.id==='championsWeeklyRankingBoard',nations=board.id==='nationsRankingBoard'||board.id==='nationsWeeklyRankingBoard',selectedWeek=champions?+(root.BizimSkorChampionsUI?.currentWeek?.()||board.querySelector?.('[data-profile-week]')?.dataset.profileWeek||1):nations?+(root.BizimSkorNationsUI?.currentWeek?.()||board.querySelector?.('[data-profile-week]')?.dataset.profileWeek||1):board.id==='weeklyRankingBoard'?+(board.ownerDocument?.getElementById('weeklyRankingWeekSelect')?.value||0):null;board.querySelectorAll?.('table tr').forEach(row=>{const cell=row.cells?.[1];if(!cell||cell.querySelector?.('.bs-player-profile-link')||cell.tagName==='TH')return;const name=(cell.textContent||'').replace(/\s*•\s*Sen\s*$/i,'').trim();if(name)cell.innerHTML=playerButton(name,selectedWeek,nations?'nations':champions?'champions':null)})}
function decorateAll(doc=document){BOARD_IDS.forEach(id=>{const board=doc.getElementById(id);if(board)decorateBoard(board)})}
async function openProfile(name,doc=document,week,kind){const shell=ensureShell(doc),card=shell.querySelector('.bs-profile-card'),token=root.localStorage?.getItem('bizimSkorFriendToken');shell.classList.remove('hide');card.innerHTML='<p class="small">Oyuncu profili yükleniyor…</p>';if(!token){card.innerHTML='<div class="bs-profile-head"><h2>Yeniden giriş gerekli</h2><button type="button" data-player-profile-close>×</button></div><p>Oyuncu profillerini görmek için hesabına yeniden giriş yap.</p>';return null}const request=profileRequest(token,name,week,kind);const q=await root.sb.rpc(request.rpc,request.args);if(q.error){card.innerHTML=`<div class="bs-profile-head"><h2>Profil açılamadı</h2><button type="button" data-player-profile-close>×</button></div><p>${esc(q.error.message)}</p>`;return null}const model=buildModel(q.data||[]);card.innerHTML=profileMarkup(model);return model}
function close(doc=document){doc.getElementById('bsPlayerProfileModal')?.classList.add('hide')}
function mount(doc=typeof document!=='undefined'?document:null){if(!doc)return;ensureShell(doc);decorateAll(doc);new MutationObserver(()=>decorateAll(doc)).observe(doc.body,{childList:true,subtree:true});doc.addEventListener('click',event=>{const closeButton=event.target.closest?.('[data-player-profile-close]');if(closeButton){close(doc);return}const link=event.target.closest?.('.bs-player-profile-link');if(link)openProfile(link.dataset.playerName,doc,link.dataset.profileWeek?+link.dataset.profileWeek:null,link.dataset.profileKind||null).catch(error=>console.warn('player profile',error))});doc.addEventListener('keydown',event=>{if(event.key==='Escape')close(doc)})}
return Object.freeze({BOARD_IDS,matchSymbol,playerButton,profileRpcArgs,championsProfileRpcArgs,nationsProfileRpcArgs,profileRequest,buildModel,profileStatsMarkup,profileMarkup,decorateBoard,decorateAll,openProfile,close,mount});
});