const fs=require('fs');
const assert=require('assert');
const bootstrap=fs.readFileSync('supported-team-bootstrap.js','utf8');
const supported=fs.readFileSync('supported-team-ui.js','utf8');
const identity=fs.readFileSync('player-identity.js','utf8');
const hooks=fs.readFileSync('player-identity-render-hooks.js','utf8');
const general=fs.readFileSync('general-ranking-weekly-total.js','utf8');
assert(bootstrap.includes("'player-identity.js'"),'player identity renderer bootstrap üzerinden yüklenmeli');
assert(bootstrap.includes("'player-identity-render-hooks.js'"),'render hookları bootstrap üzerinden yüklenmeli');
assert(!bootstrap.includes("'supported-team-ranking-logos.js'"),'eski DOM logo tarayıcısı yüklenmemeli');
assert(!supported.includes('new MutationObserver'),'takım seçimi tüm sayfayı izlememeli');
assert(identity.includes('function markup'),'logo+isim aynı kimlik markupında üretilmeli');
assert(identity.includes('bs-supported-team-logo'),'takım logosu kimliğin parçası olmalı');
assert(!identity.includes('MutationObserver'),'kimlik modülü DOM gözlemlememeli');
assert(hooks.includes('renderScoreTable'),'Süper Lig sıralaması render anında kimliği kullanmalı');
assert(hooks.includes('renderFriendLeagueRanking'),'arkadaş ligi render anında kimliği kullanmalı');
assert(hooks.includes('championsRankingBoard'),'Şampiyonlar Ligi renderı hedeflenmeli');
assert(hooks.includes('nationsRankingBoard'),'Uluslar Ligi renderı hedeflenmeli');
assert(hooks.includes('leagueSystemPanel'),'Arena renderı hedeflenmeli');
assert(hooks.includes('bsPlayerMuseumModal'),'Müze renderı hedeflenmeli');
assert(general.includes('BizimSkorPlayerIdentity'),'genel sıralama doğrudan ortak kimlik renderer kullanmalı');
console.log('render-time player identity contract ok');
