(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BizimSkorPlayerMuseum=api;api.mount();}})(typeof globalThis!=='undefined'?globalThis:this,function(root){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LEAGUES={champions:'Şampiyonlar',elite:'Elit Lig',gold:'Altın Lig',silver:'Gümüş Lig',bronze:'Bronz Lig'};
let previousProfileHtml='';
function medal(rank){return +rank===1?'🥇':+rank===2?'🥈':+rank===3?'🥉':''}
function cabinetMarkup(c={}){return `<section class="bs-museum-section"><h3>🏆 Kupa Dolabı</h3><div class="bs-museum-cabinet"><div><b>🥇 ${+c.gold||0}</b><span>Birincilik</span></div><div><b>🥈 ${+c.silver||0}</b><span>İkincilik</span></div><div><b>🥉 ${+c.bronze||0}</b><span>Üçüncülük</span></div><div><b>🏆 ${+c.arena_championships||0}</b><span>Arena Şampiyonluğu</span></div></div></section>`}
function weeklyMarkup(rows=[]){return `<section class="bs-museum-section"><h3>🎯 Haftalık Dereceler</h3>${rows.length?rows.map(x=>`<div class="bs-museum-row"><span>${esc(x.competition)} • ${esc(x.week)}. Hafta</span><b>${medal(x.rank)} ${esc(x.rank)}.</b></div>`).join(''):'<p class="small">Henüz kesinleşmiş ilk üç derecesi yok.</p>'}</section>`}
function arenaDetail(x){if(x.from_league&&x.to_league&&x.from_league!==x.to_league)return `${LEAGUES[x.from_league]||x.from_league} → ${LEAGUES[x.to_league]||x.to_league}`;if(x.league_code)return LEAGUES[x.league_code]||x.league_code;return ''}
function arenaMarkup(rows=[]){return `<section class="bs-museum-section"><h3>⚔️ Arena Başarıları</h3>${rows.length?rows.map(x=>`<div class="bs-museum-row"><span>${esc(x.season_no)}. Sezon (${esc(x.weeks)})${x.is_final?'':' • Devam ediyor'}${arenaDetail(x)?`<small>${esc(arenaDetail(x))}</small>`:''}</span><b>${medal(x.rank)} ${esc(x.rank)}.</b></div>`).join(''):'<p class="small">Henüz Arena başarısı yok.</p>'}</section>`}
function generalMarkup(rows=[]){return `<section class="bs-museum-section"><h3>📊 Genel Sıralama</h3>${rows.length?rows.map(x=>`<div class="bs-museum-row"><span>${esc(x.competition)}</span><b>${x.rank?`${esc(x.rank)}.`:'—'}</b></div>`).join(''):'<p class="small">Genel sıralama verisi bulunamadı.</p>'}</section>`}
function renderMuseum(data={},standalone=false){const action=standalone?'<button type="button" class="bs-museum-close" data-player-museum-close aria-label="Müzeyi kapat">×</button>':'<button type="button" data-player-museum-back>← Profil</button>';return `<div class="bs-museum-head"><div><span>OYUNCU MÜZESİ</span><h2>🏛️ ${esc(data.player_name||'Oyuncu')}</h2></div>${action}</div>${cabinetMarkup(data.trophy_cabinet)}${weeklyMarkup(data.weekly_achievements||[])}${arenaMarkup(data.arena_achievements||[])}${generalMarkup(data.general_rankings||[])}`}
function ensureStyle(doc){if(doc.getElementById('bsPlayerMuseumStyles'))return;doc.head.insertAdjacentHTML('beforeend','<style id="bsPlayerMuseumStyles">.bs-profile-head .bs-profile-title-row{display:flex;align-items:center;gap:10px;flex-wrap:nowrap;min-width:0;max-width:calc(100% - 52px)}.bs-profile-head .bs-profile-title-row h2{margin:4px 0 14px;min-width:0}.bs-profile-head .bs-profile-museum-open{appearance:none!important;width:auto!important;height:auto!important;min-width:0!important;min-height:0!important;margin:0 0 10px!important;padding:7px 11px!important;background:#fff7ed!important;color:#9a3412!important;border:1px solid #fed7aa!important;border-radius:999px!important;font-size:12px!important;line-height:1!important;white-space:nowrap!important;flex:0 0 auto!important}.bs-museum-modal{position:fixed;inset:0;z-index:10030;display:flex;align-items:flex-end;justify-content:center}.bs-museum-modal.hide{display:none}.bs-museum-backdrop{position:absolute;inset:0;background:rgba(3,12,28,.64);backdrop-filter:blur(3px)}.bs-museum-card{position:relative;width:min(100%,560px);max-height:90vh;overflow:auto;background:#f8fafc;border-radius:24px 24px 0 0;padding:20px;color:#0f172a;box-shadow:0 -16px 50px rgba(0,0,0,.25)}.bs-museum-head{display:flex;justify-content:space-between;align-items:flex-start}.bs-museum-head span{font-size:11px;letter-spacing:2px;color:#64748b;font-weight:900}.bs-museum-head h2{margin:4px 0 12px}.bs-museum-head button{padding:9px 11px;background:#e2e8f0;border:0;border-radius:12px;font-weight:800}.bs-museum-head .bs-museum-close{border-radius:50%;width:38px;height:38px;padding:0;font-size:26px;line-height:38px}.bs-museum-section{margin-top:14px;padding:13px;border-radius:16px;background:#fff;border:1px solid #e2e8f0}.bs-museum-section h3{margin:0 0 10px}.bs-museum-cabinet{display:grid;grid-template-columns:1fr 1fr;gap:8px}.bs-museum-cabinet div{padding:11px;text-align:center;border-radius:12px;background:#f8fafc}.bs-museum-cabinet b,.bs-museum-cabinet span{display:block}.bs-museum-cabinet b{font-size:20px}.bs-museum-cabinet span,.bs-museum-row small{font-size:10px;color:#64748b;margin-top:4px}.bs-museum-row{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-top:1px solid #eef2f7}.bs-museum-row:first-of-type{border-top:0}.bs-museum-row small{display:block}@media(min-width:620px){.bs-museum-modal{align-items:center}.bs-museum-card{border-radius:24px}}</style>')}
function ensureMuseumShell(doc){let shell=doc.getElementById('bsPlayerMuseumModal');if(shell)return shell;shell=doc.createElement('div');shell.id='bsPlayerMuseumModal';shell.className='bs-museum-modal hide';shell.innerHTML='<div class="bs-museum-backdrop" data-player-museum-close></div><div class="bs-museum-card" role="dialog" aria-modal="true" aria-live="polite"><p class="small">Müze yükleniyor…</p></div>';doc.body.appendChild(shell);return shell}
async function openMuseum(name,doc=typeof document!=='undefined'?document:null){const clean=String(name||'').trim();if(!doc||!clean)return null;ensureStyle(doc);const shell=ensureMuseumShell(doc),card=shell.querySelector('.bs-museum-card'),token=root.localStorage?.getItem('bizimSkorFriendToken');shell.classList.remove('hide');card.innerHTML='<p class="small">Müze yükleniyor…</p>';if(!token){card.innerHTML='<div class="bs-museum-head"><h2>Yeniden giriş gerekli</h2><button type="button" class="bs-museum-close" data-player-museum-close>×</button></div><p>Müzeyi görmek için hesabına yeniden giriş yap.</p>';return null}const q=await root.sb.rpc('get_player_museum',{p_token:token,p_player_name:clean});if(q.error){card.innerHTML=`<div class="bs-museum-head"><h2>Müze açılamadı</h2><button type="button" class="bs-museum-close" data-player-museum-close>×</button></div><p>${esc(q.error.message)}</p>`;return null}card.innerHTML=renderMuseum(q.data||{},true);return q.data||{}}
function closeMuseum(doc=typeof document!=='undefined'?document:null){doc?.getElementById('bsPlayerMuseumModal')?.classList.add('hide')}
function addMuseumButton(card,name){if(!card||!name||card.querySelector('[data-player-museum-open]'))return;const head=card.querySelector('.bs-profile-head'),title=head?.querySelector('h2');if(!head||!title)return;let row=head.querySelector('.bs-profile-title-row');if(!row){row=card.ownerDocument.createElement('div');row.className='bs-profile-title-row';title.parentNode.insertBefore(row,title);row.appendChild(title)}row.insertAdjacentHTML('beforeend',`<button type="button" class="bs-profile-museum-open" data-player-museum-open="${esc(name)}">🏛️ Müze</button>`)}
function enhance(doc){const card=doc.querySelector('#bsPlayerProfileModal .bs-profile-card'),head=card?.querySelector('.bs-profile-head h2');if(head)addMuseumButton(card,head.textContent.trim())}
function mount(doc=typeof document!=='undefined'?document:null){if(!doc)return;ensureStyle(doc);ensureMuseumShell(doc);enhance(doc);new MutationObserver(()=>enhance(doc)).observe(doc.body,{childList:true,subtree:true});doc.addEventListener('click',async e=>{const close=e.target.closest?.('[data-player-museum-close]');if(close){closeMuseum(doc);return}const open=e.target.closest?.('[data-player-museum-open]');if(open){const name=open.dataset.playerMuseumOpen;if(open.id==='bsHeaderMuseumAction'){e.preventDefault();e.stopImmediatePropagation();await openMuseum(name,doc);return}const card=open.closest('.bs-profile-card'),token=root.localStorage?.getItem('bizimSkorFriendToken');if(!card||!token)return;previousProfileHtml=card.innerHTML;card.innerHTML='<p class="small">Müze yükleniyor…</p>';const q=await root.sb.rpc('get_player_museum',{p_token:token,p_player_name:name});if(q.error){card.innerHTML=previousProfileHtml;enhance(doc);return}card.innerHTML=renderMuseum(q.data||{});return}const back=e.target.closest?.('[data-player-museum-back]');if(back){const card=back.closest('.bs-profile-card');if(card&&previousProfileHtml){card.innerHTML=previousProfileHtml;enhance(doc)}}},true);doc.addEventListener('keydown',e=>{if(e.key==='Escape')closeMuseum(doc)})}
return Object.freeze({medal,cabinetMarkup,weeklyMarkup,arenaDetail,arenaMarkup,generalMarkup,renderMuseum,mount,openMuseum,closeMuseum,addMuseumButton,enhance});
});