const assert=require('assert');
const fs=require('fs');
const overlay=fs.readFileSync(require.resolve('./dashboard-five-card-overlay.js'),'utf8');
const premium=fs.readFileSync(require.resolve('./premium-reference-ui.js'),'utf8');
assert.match(overlay,/grid-template-columns:repeat\(4,minmax\(0,1fr\)\)!important/i,'Dashboard must use a stable four-column mobile grid');
assert.match(overlay,/\.bs-home-stat\.champions\{[^}]*order:1;grid-column:1 \/ span 2/i,'Champions card must occupy the left half of the first row');
assert.match(overlay,/\.bs-home-stat\.general\{[^}]*order:2;grid-column:3 \/ span 2/i,'Super League general card must occupy the right half of the first row');
assert.match(overlay,/\.bs-home-stat\.nations\{[^}]*order:3;grid-column:2 \/ span 2/i,'Nations League card must be centered on its own row');
assert.match(overlay,/\.bs-home-stat\.league\{[^}]*order:4;grid-column:1 \/ span 2/i,'Weekly Super League card must occupy the left half of the last row');
assert.match(overlay,/\.bs-home-stat\.rate\{[^}]*order:5;grid-column:3 \/ span 2/i,'Result rate card must occupy the right half of the last row');
assert.match(overlay,/\.bs-home-stat\.admin-statistics\{display:none!important\}/i,'Admin summary must stay hidden');
assert.doesNotMatch(overlay,/\.bs-home-stat\.general,#bsHomeDashboard \.bs-home-stat\.nations[^\n]*display:none/i,'General and Nations cards must not be hidden by the five-card overlay');
assert.doesNotMatch(premium,/#bsHomeDashboard \.bs-home-stat\.general,#bsHomeDashboard \.bs-home-stat\.nations[^\n]*display:none!important/i,'Premium styles must not hide General or Nations cards');
console.log('premium reference dashboard layout ok');
