(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BizimSkorShareGame=api;api.start()}})(typeof globalThis!=='undefined'?globalThis:this,function(root){
const fallbackUrl='https://bizim-skor-live.vercel.app';
function currentGameUrl(host=root){const origin=host?.location?.origin,pathname=host?.location?.pathname;return origin&&origin!=='null'?`${origin}${pathname||'/'}`:fallbackUrl}
function personalInviteUrl(host=root){const name=host?.localStorage?.getItem?.('bizimSkorName')||'';const url=new URL(currentGameUrl(host));if(name)url.searchParams.set('invite',name);return url.toString()}
function shareText(url=personalInviteUrl()){return `⚽ Bizim Skor’a sen de katıl!\nSüper Lig ve Şampiyonlar Ligi maçlarının skorlarını tahmin et, arkadaşlarınla yarış. 🎯\n${url}`}
function whatsappUrl(url=personalInviteUrl()){return `https://wa.me/?text=${encodeURIComponent(shareText(url))}`}
function recordShareClick(host=root){const token=host?.localStorage?.getItem?.('bizimSkorFriendToken')||'';if(!token||typeof host?.sb?.rpc!=='function')return false;Promise.resolve(host.sb.rpc('record_game_share_click',{p_token:token,p_channel:'whatsapp'})).catch(()=>{});return true}
function leagueChoices(doc=typeof document!=='undefined'?document:null){const select=doc?.getElementById?.('friendLeagueSelect');return Array.from(select?.options||[]).filter(o=>String(o.value||'').trim()).map(o=>({id:String(o.value),name:String(o.textContent||o.value).trim()}))}
function styleMarkup(){return '<style id="bsShareGameStyles">.bs-connection-share-row{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:8px;align-items:stretch;margin-bottom:12px}.bs-connection-share-row #conn{display:flex;align-items:center;min-width:0;min-height:48px;box-sizing:border-box;margin:0;padding:10px 12px;font-size:14px}.bs-share-wrap{position:relative}.bs-share-game{width:100%;min-height:48px;border:1px solid #16a34a;border-radius:14px;background:linear-gradient(135deg,#22c55e,#15803d);color:#fff;font-size:14px;font-weight:900}.bs-share-menu{position:absolute;z-index:30;right:0;top:54px;width:min(290px,82vw);padding:8px;border-radius:14px;background:#fff;box-shadow:0 14px 38px rgba(15,23,42,.22);border:1px solid #e2e8f0}.bs-share-menu.hide{display:none}.bs-share-menu button{width:100%;margin:4px 0;padding:11px;border:0;border-radius:10px;text-align:left;font-weight:800;background:#f8fafc;color:#0f172a}.bs-league-title{padding:7px 8px 3px;font-size:12px;font-weight:900;color:#64748b}.bs-league-choice{background:#eff6ff!important;color:#1d4ed8!important}</style>'}
async function shareGame(host=root){const url=personalInviteUrl(host);recordShareClick(host);if(host?.navigator?.share){try{await host.navigator.share({title:'Bizim Skor',text:shareText(url),url});return true}catch(e){if(e?.name==='AbortError')return false}}host?.open?.(whatsappUrl(url),'_blank','noopener,noreferrer');return true}
async function shareLeagueById(leagueId,host=root,doc=typeof document!=='undefined'?document:null){const select=doc?.getElementById?.('friendLeagueSelect');if(!select)return false;select.value=leagueId;try{select.dispatchEvent(new Event('change',{bubbles:true}))}catch(e){select.onchange?.()}await new Promise(resolve=>setTimeout(resolve,180));const helper=host?.BizimSkorLeagueInviteShare;return helper?.shareSelectedLeague?!!(await helper.shareSelectedLeague(host,doc)):false}
async function shareSelectedLeagueFromMenu(host=root,doc=typeof document!=='undefined'?document:null){const helper=host?.BizimSkorLeagueInviteShare;if(helper?.shareSelectedLeague){const shared=await helper.shareSelectedLeague(host,doc);if(shared)return true}doc?.querySelector?.('[data-tab="friendLeagues"]')?.click();return false}
function renderLeagueChoices(menu,host,doc){menu.querySelectorAll?.('[data-league-choice],.bs-league-title')?.forEach(el=>el.remove());const choices=leagueChoices(doc);if(!choices.length){doc?.querySelector?.('[data-tab="friendLeagues"]')?.click();host?.alert?.('Önce Arkadaş Liglerim bölümünden bir lige katıl veya lig oluştur.');menu.classList.add('hide');return false}const title=doc.createElement('div');title.className='bs-league-title';title.textContent='Hangi lige davet edeceksin?';menu.appendChild(title);choices.forEach(choice=>{const b=doc.createElement('button');b.type='button';b.className='bs-league-choice';b.dataset.leagueChoice=choice.id;b.textContent='👥 '+choice.name;b.onclick=()=>{menu.classList.add('hide');shareLeagueById(choice.id,host,doc).then(ok=>{if(!ok){doc?.querySelector?.('[data-tab="friendLeagues"]')?.click();host?.alert?.('Lig daveti hazırlanamadı. Arkadaş Liglerim ekranından tekrar deneyebilirsin.')}}).catch(e=>host.alert?.('Lig daveti paylaşılamadı: '+e.message))};menu.appendChild(b)});return true}
function mount(doc=typeof document!=='undefined'?document:null,host=root){if(!doc||doc.getElementById('bsShareGame'))return false;const connection=doc.getElementById('conn');if(!connection)return false;const row=doc.createElement('div');row.id='bsConnectionShareRow';row.className='bs-connection-share-row';const wrap=doc.createElement('div');wrap.className='bs-share-wrap';const button=doc.createElement('button');button.id='bsShareGame';button.className='bs-share-game';button.type='button';button.textContent='🟢 Oyunu Arkadaşına Öner';const menu=doc.createElement('div');menu.id='bsShareMenu';menu.className='bs-share-menu hide';const game=doc.createElement('button');game.type='button';game.textContent='⚽ Oyuna Davet Et';game.onclick=()=>{menu.classList.add('hide');shareGame(host)};const league=doc.createElement('button');league.type='button';league.textContent='👥 Arkadaş Ligine Davet Et';league.onclick=()=>renderLeagueChoices(menu,host,doc);menu.appendChild(game);menu.appendChild(league);button.onclick=()=>{menu.classList.toggle('hide');menu.querySelectorAll?.('[data-league-choice],.bs-league-title')?.forEach(el=>el.remove())};connection.insertAdjacentElement('beforebegin',row);row.appendChild(connection);wrap.appendChild(button);wrap.appendChild(menu);row.appendChild(wrap);if(!doc.getElementById('bsShareGameStyles'))doc.head.insertAdjacentHTML('beforeend',styleMarkup());return true}
function start(){if(typeof document==='undefined')return;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>mount(),{once:true});else mount()}
return Object.freeze({shareText,whatsappUrl,currentGameUrl,personalInviteUrl,recordShareClick,leagueChoices,shareGame,shareLeagueById,shareSelectedLeagueFromMenu,renderLeagueChoices,styleMarkup,mount,start});});
