(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BizimSkorShareGame=api;api.start()}})(typeof globalThis!=='undefined'?globalThis:this,function(root){
const fallbackUrl='https://bizim-skor-live.vercel.app';
function currentGameUrl(host=root){const origin=host?.location?.origin,pathname=host?.location?.pathname;return origin&&origin!=='null'?`${origin}${pathname||'/'}`:fallbackUrl}
function personalInviteUrl(host=root){const name=host?.localStorage?.getItem?.('bizimSkorName')||'';const url=new URL(currentGameUrl(host));if(name)url.searchParams.set('invite',name);return url.toString()}
function shareText(url=personalInviteUrl()){return `⚽ Bizim Skor’a sen de katıl!\nSüper Lig ve Şampiyonlar Ligi maçlarının skorlarını tahmin et, arkadaşlarınla yarış. 🎯\n${url}`}
function whatsappUrl(url=personalInviteUrl()){return `https://wa.me/?text=${encodeURIComponent(shareText(url))}`}
function recordShareClick(host=root){const token=host?.localStorage?.getItem?.('bizimSkorFriendToken')||'';if(!token||typeof host?.sb?.rpc!=='function')return false;Promise.resolve(host.sb.rpc('record_game_share_click',{p_token:token,p_channel:'whatsapp'})).catch(()=>{});return true}
function styleMarkup(){return '<style id="bsShareGameStyles">.bs-connection-share-row{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:8px;align-items:stretch;margin-bottom:12px}.bs-connection-share-row #conn{display:flex;align-items:center;min-width:0;min-height:48px;box-sizing:border-box;margin:0;padding:10px 12px;font-size:14px}.bs-share-wrap{position:relative}.bs-share-game{width:100%;min-height:48px;border:1px solid #16a34a;border-radius:14px;background:linear-gradient(135deg,#22c55e,#15803d);color:#fff;font-size:14px;font-weight:900}.bs-share-menu{position:absolute;z-index:30;right:0;top:54px;width:min(270px,78vw);padding:8px;border-radius:14px;background:#fff;box-shadow:0 14px 38px rgba(15,23,42,.22);border:1px solid #e2e8f0}.bs-share-menu.hide{display:none}.bs-share-menu button{width:100%;margin:4px 0;padding:11px;border:0;border-radius:10px;text-align:left;font-weight:800;background:#f8fafc;color:#0f172a}</style>'}
async function shareGame(host=root){const url=personalInviteUrl(host);recordShareClick(host);if(host?.navigator?.share){try{await host.navigator.share({title:'Bizim Skor',text:shareText(url),url});return}catch(e){if(e?.name==='AbortError')return}}host?.open?.(whatsappUrl(url),'_blank','noopener,noreferrer')}
function mount(doc=typeof document!=='undefined'?document:null,host=root){if(!doc||doc.getElementById('bsShareGame'))return false;const connection=doc.getElementById('conn');if(!connection)return false;const row=doc.createElement('div');row.id='bsConnectionShareRow';row.className='bs-connection-share-row';const wrap=doc.createElement('div');wrap.className='bs-share-wrap';const button=doc.createElement('button');button.id='bsShareGame';button.className='bs-share-game';button.type='button';button.textContent='🟢 Oyunu Arkadaşına Öner';const menu=doc.createElement('div');menu.id='bsShareMenu';menu.className='bs-share-menu hide';const game=doc.createElement('button');game.type='button';game.textContent='⚽ Oyuna Davet Et';game.onclick=()=>shareGame(host);const league=doc.createElement('button');league.type='button';league.textContent='👥 Bu Lige Davet Et';league.onclick=()=>doc.querySelector?.('[data-tab="friendLeagues"]')?.click();menu.appendChild(game);menu.appendChild(league);button.onclick=()=>menu.classList.toggle('hide');connection.insertAdjacentElement('beforebegin',row);row.appendChild(connection);wrap.appendChild(button);wrap.appendChild(menu);row.appendChild(wrap);if(!doc.getElementById('bsShareGameStyles'))doc.head.insertAdjacentHTML('beforeend',styleMarkup());return true}
function start(){if(typeof document==='undefined')return;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>mount(),{once:true});else mount()}
return Object.freeze({shareText,whatsappUrl,currentGameUrl,personalInviteUrl,recordShareClick,shareGame,styleMarkup,mount,start});});
