-- Bizim Skor invite growth subsystem.
-- Additive only: does not alter prediction, scoring, player or friend-league tables.

create table if not exists public.invite_attributions (
  id bigint generated by default as identity primary key,
  inviter_id text not null,
  invited_player_id text not null unique,
  league_id text null,
  created_at timestamptz not null default now(),
  constraint invite_attributions_no_self_invite check (inviter_id <> invited_player_id)
);

create index if not exists invite_attributions_inviter_created_idx
  on public.invite_attributions (inviter_id, created_at desc);

alter table public.invite_attributions enable row level security;

revoke insert, update, delete on public.invite_attributions from anon, authenticated;
grant select on public.invite_attributions to authenticated;

-- The app should call this RPC only from its trusted registration integration.
-- SECURITY INVOKER is intentional; the calling integration must use a role that
-- is allowed to insert, while browser roles retain read-only access.
create or replace function public.record_invite_attribution(
  p_inviter_id text,
  p_invited_player_id text,
  p_league_id text default null
)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  inserted_count integer;
begin
  if p_inviter_id is null or p_invited_player_id is null or p_inviter_id = p_invited_player_id then
    return false;
  end if;

  insert into public.invite_attributions (inviter_id, invited_player_id, league_id)
  values (p_inviter_id, p_invited_player_id, p_league_id)
  on conflict (invited_player_id) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

revoke execute on function public.record_invite_attribution(text, text, text) from public, anon, authenticated;
grant execute on function public.record_invite_attribution(text, text, text) to service_role;

create or replace function public.get_invite_leaderboard(
  p_start_at timestamptz default null,
  p_end_at timestamptz default null
)
returns table (inviter_id text, invite_count bigint)
language sql
security invoker
set search_path = ''
as $$
  select ia.inviter_id, count(*)::bigint as invite_count
  from public.invite_attributions ia
  where (p_start_at is null or ia.created_at >= p_start_at)
    and (p_end_at is null or ia.created_at < p_end_at)
  group by ia.inviter_id
  order by invite_count desc, ia.inviter_id asc;
$$;

revoke execute on function public.get_invite_leaderboard(timestamptz, timestamptz) from public, anon;
grant execute on function public.get_invite_leaderboard(timestamptz, timestamptz) to authenticated, service_role;
