(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else{root.BizimSkorSupportedTeam=api;api.mount();}})(typeof globalThis!=='undefined'?globalThis:this,function(root){
const TEAMS=Object.freeze([{code:'galatasaray',name:'Galatasaray'},{code:'fenerbahce',name:'Fenerbahçe'},{code:'besiktas',name:'Beşiktaş'},{code:'trabzonspor',name:'Trabzonspor'},{code:'basaksehir',name:'Başakşehir'},{code:'kasimpasa',name:'Kasımpaşa'},{code:'alanyaspor',name:'Alanyaspor'},{code:'rizespor',name:'Çaykur Rizespor'},{code:'gaziantep',name:'Gaziantep FK'},{code:'konyaspor',name:'Konyaspor'},{code:'samsunspor',name:'Samsunspor'},{code:'eyupspor',name:'Eyüpspor'},{code:'goztepe-izmir',name:'Göztepe'},{code:'genclerbirligi',name:'Gençlerbirliği'},{code:'amed-sk',name:'Amed SK'},{code:'corum-fk',name:'Çorum FK'},{code:'kocaelispor',name:'Kocaelispor'},{code:'erzurumspor',name:'Erzurumspor'}]);
const byCode=new Map(TEAMS.map(x=>[x.code,x]));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const LOGO_OVERRIDES=Object.freeze({kocaelispor:'https://kocaelispor.com.tr/images/upload/7cad04d86cb9f4219a0e635b47121d2f.png',erzurumspor:'https://erzurumsporfk.org/wp-content/uploads/2022/08/cropped-ERZURUMSPOR-FK-kopya-3.png'});
function logoUrl(code){const team=byCode.get(code);if(!team)return'';if(LOGO_OVERRIDES[code])return LOGO_OVERRIDES[code];const branded=root.BizimSkorBrandAssets?.teamLogoUrl?.(team.name);if(branded)return branded;const slug=code==='amed-sk'?'amed':code==='corum-fk'?'corum':code;return `https://football-logos.cc/logos/turkey/256x256/${slug}.png`}
function playerLogoMarkup(code,label=''){const url=logoUrl(code);return url?`<img class="bs-supported-team-logo" src="${esc(url)}" alt="${esc(label||byCode.get(code)?.name||'Takım')}" loading="lazy" referrerpolicy="no-referrer">`:''}
function teamPickerMarkup(){return `<div class="bs-supported-team-card"><h2>Takımını seç</h2><p>Takımını seç, BizimSkor'da rengini belli et!</p><div class="bs-supported-team-grid">${TEAMS.map(t=>`<button type="button" class="bs-supported-team-choice" data-supported-team-code="${t.code}">${playerLogoMarkup(t.code,t.name)}<span>${esc(t.name)}</span></button>`).join('')}</div><p class="bs-supported-team-warning">⚠️ Takım seçimi tek seferliktir.</p><button type="button" class="bs-supported-team-save" data-supported-team-save disabled>Takımımı Kaydet</button><p data-supported-team-status></p></div>`}
function ensureStyle(doc){if(doc.getElementById('bsSupportedTeamStyles'))return;const s=doc.createElement('style');s.id='bsSupportedTeamStyles';s.textContent='.bs-supported-team-modal{position:fixed;inset:0;z-index:12000;display:flex;align-items:flex-end;justify-content:center;background:rgba(2,8,23,.72)}.bs-supported-team-modal.hide{display:none}.bs-supported-team-card{width:min(100%,580px);max-height:92vh;overflow:auto;background:#f8fafc;color:#0f172a;border-radius:24px 24px 0 0;padding:18px}.bs-supported-team-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.bs-supported-team-choice{display:flex;min-height:86px;flex-direction:column;align-items:center;justify-content:center;gap:7px;background:#fff;color:#0f172a;border:2px solid #e2e8f0;border-radius:14px;padding:9px 5px}.bs-supported-team-choice.selected{border-color:#2563eb;background:#eff6ff}.bs-supported-team-choice .bs-supported-team-logo{width:40px;height:40px}.bs-supported-team-logo{width:22px;height:22px;object-fit:contain;display:inline-block;vertical-align:middle}.bs-supported-team-warning{font-size:11px;color:#92400e;background:#fffbeb;padding:9px;border-radius:10px}.bs-supported-team-save{width:100%;background:#0f172a;color:#fff}.bs-supported-team-save:disabled{opacity:.45}@media(min-width:620px){.bs-supported-team-modal{align-items:center}.bs-supported-team-card{border-radius:24px}.bs-supported-team-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}';doc.head.appendChild(s)}
function ensureModal(doc){let modal=doc.getElementById('bsSupportedTeamModal');if(modal)return modal;modal=doc.createElement('div');modal.id='bsSupportedTeamModal';modal.className='bs-supported-team-modal hide';modal.innerHTML=teamPickerMarkup();doc.body.appendChild(modal);return modal}
let cachedContext=null,loading=null;
async function loadContext(){const token=root.localStorage?.getItem('bizimSkorFriendToken');if(!token||!root.sb)return null;if(cachedContext)return cachedContext;if(loading)return loading;loading=root.sb.rpc('get_supported_team_context',{p_token:token}).then(q=>{loading=null;if(q.error)throw q.error;cachedContext=q.data||{};return cachedContext}).catch(e=>{loading=null;throw e});return loading}
async function refresh(doc){const ctx=await loadContext();if(ctx&&!ctx.current_team)ensureModal(doc).classList.remove('hide');return ctx}
async function saveChoice(doc,code){const token=root.localStorage?.getItem('bizimSkorFriendToken');if(!token)return;const q=await root.sb.rpc('set_supported_team_once',{p_token:token,p_team_code:code});if(q.error)throw q.error;cachedContext=null;await loadContext();ensureModal(doc).classList.add('hide');root.dispatchEvent?.(new Event('supported-team:saved'))}
function mount(doc=typeof document!=='undefined'?document:null){if(!doc)return false;ensureStyle(doc);const modal=ensureModal(doc);let selected='';modal.addEventListener('click',async e=>{const choice=e.target.closest?.('[data-supported-team-code]');if(choice){selected=choice.dataset.supportedTeamCode;modal.querySelectorAll('[data-supported-team-code]').forEach(x=>x.classList.toggle('selected',x===choice));modal.querySelector('[data-supported-team-save]').disabled=false;return}if(e.target.closest?.('[data-supported-team-save]')&&selected){const status=modal.querySelector('[data-supported-team-status]'),save=modal.querySelector('[data-supported-team-save]');save.disabled=true;status.textContent='Kaydediliyor…';try{await saveChoice(doc,selected);status.textContent=''}catch(err){status.textContent=err?.message||'Takım kaydedilemedi.';save.disabled=false}}});setTimeout(()=>refresh(doc).catch(e=>console.warn('supported team',e)),600);root.addEventListener?.('bizimskor:session-ready',()=>{cachedContext=null;loading=null;setTimeout(()=>refresh(doc).catch(()=>{}),100)});return true}
return Object.freeze({TEAMS,LOGO_OVERRIDES,logoUrl,playerLogoMarkup,teamPickerMarkup,loadContext,refresh,mount});
});
