const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('supported-team-ranking-logos.js','utf8');
const boot=fs.readFileSync('supported-team-bootstrap.js','utf8');
assert(src.includes('#weeklyRankingBoard table tr td:nth-child(2)'),'haftalık sıralamanın gerçek oyuncu sütunu hedeflenmeli');
assert(src.includes('#generalBoard table tr td:nth-child(2)'),'genel sıralamanın gerçek oyuncu sütunu hedeflenmeli');
assert(src.includes('.league-player'),'Arena oyuncu adı hedeflenmeli');
assert(src.includes('.bs-museum-head h2'),'Müze başlığı hedeflenmeli');
assert(src.includes("get_supported_team_context"),'takım verisi tek bağlam sorgusundan alınmalı');
assert(src.includes("if(map)return map"),'takım verisi önbellekte tutulmalı');
assert(src.includes(".bs-supported-team-logo"),'aynı logo tekrar eklenmemeli');
assert(boot.includes("supported-team-ranking-logos.js"),'ranking logo dosyası izole bootstrap tarafından yüklenmeli');
assert(!boot.includes('ui-integration-loader.js'),'genel UI loader yeniden devreye sokulmamalı');
console.log('supported team ranking logos ok');
