const fs=require('fs');
const assert=require('assert');
const src=fs.readFileSync('supported-team-ranking-logos.js','utf8');
const boot=fs.readFileSync('supported-team-bootstrap.js','utf8');
assert(src.includes('tablePlayerCells'),'oyuncu sütunu tablo başlığına göre bulunmalı');
assert(src.includes("label==='oyuncu'||label==='katilimci'"),'Oyuncu ve Katılımcı başlıkları desteklenmeli');
assert(src.includes('.league-player'),'Arena oyuncu adı hedeflenmeli');
assert(src.includes('.bs-museum-head h2'),'Müze başlığı hedeflenmeli');
assert(src.includes("get_supported_team_context"),'takım verisi tek bağlam sorgusundan alınmalı');
assert(src.includes("if(map)return map"),'takım verisi önbellekte tutulmalı');
assert(src.includes(".bs-supported-team-logo"),'aynı logo tekrar eklenmemeli');
assert(!boot.includes("supported-team-ranking-logos.js"),'eski DOM tarayıcısı bootstrap tarafından yüklenmemeli');
assert(!boot.includes('ui-integration-loader.js'),'genel UI loader yeniden devreye sokulmamalı');
console.log('supported team ranking logos ok');
