const assert=require('assert');
const ui=require('./weekly-ranking-strip.js');
assert.deepStrictEqual(ui.availableWeeks([{week:2},{week:4},{week:3},{week:4}]),[2,3,4]);
assert.strictEqual(ui.currentWeek([2,3,4],4),4);
assert.strictEqual(ui.currentWeek([2,3,4],5),4);
assert.strictEqual(ui.currentWeek([2,3,4],null),4);
assert.strictEqual(typeof ui.latestScoredWeek,'function');
const fixtures=[{id:21,week:3},{id:31,week:4},{id:41,week:5}];
assert.strictEqual(ui.latestScoredWeek(fixtures,[{fixture_id:21,home_score:1,away_score:0}]),3);
assert.strictEqual(ui.latestScoredWeek(fixtures,[{fixture_id:21,home_score:1,away_score:0},{fixture_id:31,home_score:0,away_score:0}]),4);
assert.strictEqual(ui.latestScoredWeek(fixtures,[]),null);
assert.match(ui.renderCompetitionSwitch('champions_league'),/data-weekly-competition="champions_league"/);
assert.match(ui.renderCompetitionSwitch('champions_league'),/>Şampiyonlar Ligi</);
const markup=ui.championsWeeklyRankingMarkup([{league_rank:1,player_name:'Ayşegül',points:8,exact_count:1,correct_count:2,participant_count:45,completed_count:1,fixture_count:18}],1);
assert.match(markup,/Şampiyonlar Ligi 1\. Hafta Sıralaması/);
assert.match(markup,/data-profile-kind="champions"/);
assert.match(markup,/data-profile-week="1"/);
assert.match(markup,/Ayşegül/);
console.log('weekly-ranking-strip ok');
