(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.BizimSkorWeekStrip=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
function normalizeWeeks(weeks){return [...new Set((weeks||[]).map(Number).filter(Number.isFinite))].sort((a,b)=>a-b)}
function pickInitialWeek(weeks,current){const rows=normalizeWeeks(weeks);if(!rows.length)return null;const n=Number(current);if(rows.includes(n))return n;return rows.filter(x=>x<=n).pop()||rows[rows.length-1]}
function renderWeekStrip(weeks,current){const selected=pickInitialWeek(weeks,current);return `<div class="bs-week-strip">${normalizeWeeks(weeks).map(w=>`<button type="button" data-week="${w}" class="bs-week-chip${w===selected?' is-current':''}">${w}. Hafta</button>`).join('')}</div>`}
function centerScrollLeft(clientWidth,scrollWidth,itemLeft,itemWidth){const max=Math.max(0,scrollWidth-clientWidth);return Math.max(0,Math.min(max,itemLeft-(clientWidth-itemWidth)/2))}
function centerChip(host,chip,smooth){if(!host||!chip)return;host.scrollTo?.({left:centerScrollLeft(host.clientWidth,host.scrollWidth,chip.offsetLeft,chip.offsetWidth),behavior:smooth?'smooth':'auto'})}
function bind(host,onSelect){if(!host)return;host.querySelectorAll('.bs-week-chip').forEach(btn=>btn.addEventListener('click',()=>{host.querySelectorAll('.bs-week-chip').forEach(x=>x.classList.remove('is-current'));btn.classList.add('is-current');centerChip(host,btn,true);onSelect?.(+btn.dataset.week)}));centerChip(host,host.querySelector('.is-current'),false)}
function styleText(){return '.fixture-controls,#fixtureWeekSlot,.fixture-week-strip{min-width:0;max-width:100%}#fixtureWeekSlot,.fixture-week-strip{width:100%;overflow:hidden}.bs-week-strip{width:100%;min-width:0;max-width:100%;display:flex;gap:8px;overflow-x:auto;overflow-y:hidden;overscroll-behavior-x:contain;scroll-snap-type:x proximity;-webkit-overflow-scrolling:touch;scrollbar-width:none;box-sizing:border-box;padding:5px 2px 8px}.bs-week-strip::-webkit-scrollbar{display:none}.bs-week-chip{flex:0 0 auto;scroll-snap-align:center;border:1px solid #cbd5e1;background:#fff;color:#334155;border-radius:999px;padding:8px 13px;font-weight:800;white-space:nowrap}.bs-week-chip.is-current{background:#0f172a;color:#fff;border-color:#0f172a}';}
function ensureStyles(){if(typeof document==='undefined'||document.getElementById('bsWeekStripStyles'))return;document.head.insertAdjacentHTML('beforeend',`<style id="bsWeekStripStyles">${styleText()}</style>`)}
return Object.freeze({normalizeWeeks,pickInitialWeek,renderWeekStrip,centerScrollLeft,styleText,bind,ensureStyles});
});
