const test=require('node:test');const assert=require('node:assert/strict');const engine=require('./shot-yikim-engine.js');
test('20 true 3d levels exist',()=>{assert.equal(engine.LEVELS.length,20);});
test('level one is a real stacked tower rather than a flat row',()=>{const l=engine.LEVELS[0];assert.ok(l.blocks.length>=7);assert.ok(new Set(l.blocks.map(b=>b.position.y.toFixed(2))).size>=4);assert.ok(l.blocks.some(b=>b.size.x>=.55&&b.size.y<=.16));assert.ok(l.blocks.filter(b=>b.size.y>b.size.x).length>=2);const xs=l.blocks.map(b=>b.position.x);assert.ok(Math.max(...xs)-Math.min(...xs)<1.05);});
test('all blocks have positive 3d size and xyz position',()=>{for(const l of engine.LEVELS){for(const b of l.blocks){for(const k of ['x','y','z'])assert.ok(Number.isFinite(b.position[k]));for(const k of ['x','y','z'])assert.ok(b.size[k]>0);assert.equal('hp' in b,false);}}});
test('campaign uses natural clear thresholds so a few pieces may stay on table',()=>{for(const l of engine.LEVELS){assert.ok(Number.isInteger(l.requiredFalls));assert.ok(l.requiredFalls>0);assert.ok(l.requiredFalls<=l.blocks.length);assert.ok(l.requiredFalls/l.blocks.length>=.6);assert.ok(l.requiredFalls/l.blocks.length<=.85);}});
test('later levels get taller deeper and more complex',()=>{const l1=engine.LEVELS[0],l20=engine.LEVELS[19];assert.ok(new Set(l20.blocks.map(b=>b.position.z.toFixed(2))).size>1);assert.ok(l20.blocks.length>l1.blocks.length);assert.ok(Math.max(...l20.blocks.map(b=>b.position.y))>Math.max(...l1.blocks.map(b=>b.position.y)));});
test('shot and fallen score transitions work',()=>{let s=engine.startGame();const before=s.shotsRemaining;s=engine.recordShot(s);assert.equal(s.shotsRemaining,before-1);s=engine.recordFallen(s,2);assert.equal(s.score,200);assert.equal(s.fallenCount,2);});
test('round transition preserves score and resets fallen count',()=>{let s=engine.createStateForRound(1,700,'playing');s=engine.recordFallen(s,2);s=engine.completeRound(s);const n=engine.startNextRound(s);assert.equal(n.round,2);assert.equal(n.score,1400);assert.equal(n.fallenCount,0);});
test('final round completes campaign',()=>{let f=engine.createStateForRound(20,1000,'playing');f=engine.completeRound(f);assert.equal(f.status,'game-complete');});
