const safeInt=(value,{min=0,max=100000}={})=>{const number=Number(value);if(!Number.isInteger(number)||number<min||number>max)throw new Error('Geçersiz sayısal sağlayıcı alanı');return number;};
const text=(value,max=120)=>String(value??'').trim().slice(0,max);
const url=value=>{const candidate=text(value,500);return /^https:\/\//i.test(candidate)?candidate:''};
export function availabilityLabel(type,reason){const haystack=`${type||''} ${reason||''}`.toLocaleLowerCase('en-US');if(/yellow|sarı/.test(haystack)&&/suspend|card|ceza/.test(haystack))return 'Sarı kart cezalısı';if(/red|kırmızı/.test(haystack)&&/suspend|card|ceza/.test(haystack))return 'Kırmızı kart cezalısı';if(/suspens|ban|ceza/.test(haystack))return 'Cezalı';if(/injur|sakat|strain|hamstring|knee|ankle|muscle/.test(haystack))return 'Sakat';if(/excluded|squad|kadro/.test(haystack))return 'Kadro dışı';return 'Durumu şüpheli';}
export function normalizeStandings(response){const groups=[];for(const item of Array.isArray(response)?response:[]){const standings=item?.league?.standings;if(Array.isArray(standings))for(const group of standings)if(Array.isArray(group))groups.push(...group);}return groups.map(row=>({rank:safeInt(row?.rank,{min:1,max:200}),team_id:safeInt(row?.team?.id,{min:1,max:999999999}),team:text(row?.team?.name),logo:url(row?.team?.logo),played:safeInt(row?.all?.played,{max:100}),win:safeInt(row?.all?.win,{max:100}),draw:safeInt(row?.all?.draw,{max:100}),lose:safeInt(row?.all?.lose,{max:100}),goal_diff:safeInt(Math.abs(Number(row?.goalsDiff||0)),{max:500})*Math.sign(Number(row?.goalsDiff||0)),points:safeInt(row?.points,{max:500})})).sort((a,b)=>a.rank-b.rank);}
export function normalizeLeaderList(response,metric){if(!['goals','assists'].includes(metric))throw new Error('Geçersiz liderlik ölçütü');return (Array.isArray(response)?response:[]).map((row,index)=>{const stats=Array.isArray(row?.statistics)?row.statistics[0]:null;return{rank:index+1,player_id:safeInt(row?.player?.id,{min:1,max:999999999}),player:text(row?.player?.name),photo:url(row?.player?.photo),team_id:safeInt(stats?.team?.id,{min:1,max:999999999}),team:text(stats?.team?.name),team_logo:url(stats?.team?.logo),value:safeInt(metric==='goals'?stats?.goals?.total:stats?.goals?.assists,{max:200})};});}
export function normalizeAvailability(response){return (Array.isArray(response)?response:[]).map(row=>{const type=text(row?.type,80),reason=text(row?.reason,200),label=availabilityLabel(type,reason);return{fixture_id:safeInt(row?.fixture?.id,{min:1,max:999999999}),fixture_date:text(row?.fixture?.date,40),team_id:safeInt(row?.team?.id,{min:1,max:999999999}),team:text(row?.team?.name),team_logo:url(row?.team?.logo),player_id:safeInt(row?.player?.id,{min:1,max:999999999}),player:text(row?.player?.name),type,reason,label,certainty:label==='Durumu şüpheli'?'doubtful':'out'};});}
export function shouldRunSync({due,alreadySucceeded,remainingQuota,requiredRequests}){return due===true&&alreadySucceeded!==true&&Number.isInteger(Number(requiredRequests))&&Number(requiredRequests)>0&&Number(remainingQuota)>=Number(requiredRequests);}
export function shouldPersistCategory({category,normalized,coverageKnown=false,hasExistingSnapshot=false}){if(category==='availability')return coverageKnown===true||(Array.isArray(normalized)&&normalized.length>0)||!hasExistingSnapshot;return Array.isArray(normalized)&&normalized.length>0;}
export function shouldRunThreeHourRefresh({lastSuccessAt,now}){if(!lastSuccessAt)return true;const previous=new Date(lastSuccessAt).getTime(),current=new Date(now).getTime();if(!Number.isFinite(previous)||!Number.isFinite(current))return false;return current-previous>=3*60*60*1000;}
export function shouldRefreshAfterMatchesComplete({todayMatchCount,completedCount,alreadySucceeded}){return Number(todayMatchCount)>0&&Number(completedCount)===Number(todayMatchCount)&&alreadySucceeded!==true;}
export function providerErrorCode(errors){const keys=Object.keys(errors&&typeof errors==='object'?errors:{}).filter(key=>/^[a-z][a-z0-9_]{0,31}$/i.test(key)).map(key=>key.toLocaleLowerCase('en-US')).sort();return `provider_payload_${keys.length?keys.join('_'):'unknown'}`;}
