create table public.champions_league_fixtures (
  id bigint generated by default as identity primary key,
  season text not null,
  week integer not null check (week > 0),
  home_team text not null,
  away_team text not null,
  kickoff timestamptz not null,
  unique (season, week, home_team, away_team)
);

create index champions_league_fixtures_week_idx
  on public.champions_league_fixtures (season, week, kickoff);

create table public.champions_league_predictions (
  player_name text not null references public.players(name) on update cascade,
  fixture_id bigint not null references public.champions_league_fixtures(id) on delete cascade,
  home_score smallint not null check (home_score between 0 and 20),
  away_score smallint not null check (away_score between 0 and 20),
  updated_at timestamptz not null default now(),
  primary key (player_name, fixture_id)
);

create index champions_league_predictions_fixture_idx
  on public.champions_league_predictions (fixture_id);

create table public.champions_league_results (
  fixture_id bigint primary key references public.champions_league_fixtures(id) on delete cascade,
  home_score smallint not null check (home_score between 0 and 20),
  away_score smallint not null check (away_score between 0 and 20),
  updated_at timestamptz not null default now()
);

alter table public.champions_league_fixtures enable row level security;
alter table public.champions_league_predictions enable row level security;
alter table public.champions_league_results enable row level security;

revoke all on table public.champions_league_fixtures from anon, authenticated;
revoke all on table public.champions_league_predictions from anon, authenticated;
revoke all on table public.champions_league_results from anon, authenticated;
grant all on table public.champions_league_fixtures to service_role;
grant all on table public.champions_league_predictions to service_role;
grant all on table public.champions_league_results to service_role;

insert into public.champions_league_fixtures(season,week,home_team,away_team,kickoff) values
('2026/27', 1, 'Club Brugge', 'Aston Villa', '2026-09-08 16:45:00+00'),
('2026/27', 1, 'AEK', 'LASK', '2026-09-08 16:45:00+00'),
('2026/27', 1, 'Real Madrid', 'Inter', '2026-09-08 19:00:00+00'),
('2026/27', 1, 'Porto', 'Manchester City', '2026-09-08 19:00:00+00'),
('2026/27', 1, 'Borussia Dortmund', 'Villarreal', '2026-09-08 19:00:00+00'),
('2026/27', 1, 'Lille', 'Real Betis', '2026-09-08 19:00:00+00'),
('2026/27', 1, 'Barcelona', 'Feyenoord', '2026-09-09 16:45:00+00'),
('2026/27', 1, 'Stuttgart', 'Viking', '2026-09-09 16:45:00+00'),
('2026/27', 1, 'Liverpool', 'Atletico Madrid', '2026-09-09 19:00:00+00'),
('2026/27', 1, 'PSG', 'Slovan Bratislava', '2026-09-09 19:00:00+00'),
('2026/27', 1, 'Napoli', 'Arsenal', '2026-09-09 19:00:00+00'),
('2026/27', 1, 'Sporting CP', 'Galatasaray', '2026-09-09 19:00:00+00'),
('2026/27', 1, 'Fenerbahçe', 'Roma', '2026-09-10 16:45:00+00'),
('2026/27', 1, 'PSV', 'Shakhtar Donetsk', '2026-09-10 16:45:00+00'),
('2026/27', 1, 'Bayern Münih', 'Bodo/Glimt', '2026-09-10 19:00:00+00'),
('2026/27', 1, 'Manchester United', 'Sabah', '2026-09-10 19:00:00+00'),
('2026/27', 1, 'Como', 'Leipzig', '2026-09-10 19:00:00+00'),
('2026/27', 1, 'Slavia Prag', 'Lens', '2026-09-10 19:00:00+00')
on conflict (season,week,home_team,away_team)
do update set kickoff=excluded.kickoff;

create or replace function public.get_champions_league_week(
  p_token text,
  p_season text,
  p_week integer
) returns table(
  fixture_id bigint,
  home_team text,
  away_team text,
  kickoff timestamptz,
  predicted_home smallint,
  predicted_away smallint,
  real_home smallint,
  real_away smallint,
  is_locked boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player text;
  v_lock_time timestamptz;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  select min(f.kickoff) into v_lock_time
  from public.champions_league_fixtures f
  where f.season=p_season and f.week=p_week;
  return query
  select f.id,f.home_team,f.away_team,f.kickoff,p.home_score,p.away_score,r.home_score,r.away_score,
         coalesce(now() >= v_lock_time,false)
  from public.champions_league_fixtures f
  left join public.champions_league_predictions p on p.fixture_id=f.id and p.player_name=v_player
  left join public.champions_league_results r on r.fixture_id=f.id
  where f.season=p_season and f.week=p_week
  order by f.kickoff,f.id;
end
$$;

create or replace function public.save_champions_league_predictions(
  p_token text,
  p_season text,
  p_week integer,
  p_predictions jsonb
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player text;
  v_lock_time timestamptz;
  v_fixture_count integer;
  v_valid_count integer;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  if jsonb_typeof(p_predictions) <> 'array' then raise exception 'Tahmin listesi geçersiz'; end if;

  select min(f.kickoff),count(*) into v_lock_time,v_fixture_count
  from public.champions_league_fixtures f
  where f.season=p_season and f.week=p_week;
  if v_fixture_count=0 then raise exception 'Fikstür bulunamadı'; end if;
  if now() >= v_lock_time then raise exception 'Tahmin süresi doldu'; end if;
  if jsonb_array_length(p_predictions)<>v_fixture_count then raise exception 'Tüm maçları doldurun'; end if;

  with submitted as (
    select x.fixture_id,x.home_score,x.away_score
    from jsonb_to_recordset(p_predictions) as x(fixture_id bigint,home_score integer,away_score integer)
  )
  select count(distinct s.fixture_id) into v_valid_count
  from submitted s
  join public.champions_league_fixtures f on f.id=s.fixture_id
  where f.season=p_season and f.week=p_week
    and s.home_score between 0 and 20 and s.away_score between 0 and 20;
  if v_valid_count<>v_fixture_count then raise exception 'Tahminler eksik veya geçersiz'; end if;

  insert into public.champions_league_predictions(player_name,fixture_id,home_score,away_score,updated_at)
  select v_player,x.fixture_id,x.home_score::smallint,x.away_score::smallint,now()
  from jsonb_to_recordset(p_predictions) as x(fixture_id bigint,home_score integer,away_score integer)
  on conflict (player_name,fixture_id) do update
  set home_score=excluded.home_score,away_score=excluded.away_score,updated_at=now();
  return true;
end
$$;

create or replace function public.get_champions_league_ranking(
  p_token text,
  p_season text
) returns table(
  league_rank bigint,
  player_name text,
  points bigint,
  exact_count bigint,
  correct_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
declare v_player text;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  return query
  with scored as (
    select p.player_name,
      coalesce(sum(case
        when p.home_score=r.home_score and p.away_score=r.away_score then 4
        when r.fixture_id is not null and sign(p.home_score-p.away_score)=sign(r.home_score-r.away_score) then 1 else 0 end),0)::bigint as points,
      count(*) filter (where p.home_score=r.home_score and p.away_score=r.away_score)::bigint as exact_count,
      count(*) filter (where r.fixture_id is not null and sign(p.home_score-p.away_score)=sign(r.home_score-r.away_score))::bigint as correct_count
    from public.champions_league_predictions p
    join public.champions_league_fixtures f on f.id=p.fixture_id and f.season=p_season
    left join public.champions_league_results r on r.fixture_id=f.id
    join public.players pl on pl.name=p.player_name and coalesce(pl.is_active,true)
    group by p.player_name
  ), ranked as (
    select s.*,rank() over(order by s.points desc,s.exact_count desc,s.correct_count desc) as league_rank
    from scored s
  )
  select r.league_rank,r.player_name,r.points,r.exact_count,r.correct_count
  from ranked r order by r.league_rank,r.player_name collate "tr-TR-x-icu";
end
$$;

create or replace function public.get_champions_league_week_predictions(
  p_token text,
  p_season text,
  p_week integer
) returns table(
  player_name text,
  fixture_id bigint,
  home_team text,
  away_team text,
  kickoff timestamptz,
  predicted_home smallint,
  predicted_away smallint,
  real_home smallint,
  real_away smallint
)
language plpgsql
security definer
set search_path = ''
as $$
declare v_player text;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  return query
  select p.player_name,f.id,f.home_team,f.away_team,f.kickoff,
    case when p.player_name=v_player or r.fixture_id is not null then p.home_score else null end,
    case when p.player_name=v_player or r.fixture_id is not null then p.away_score else null end,
    r.home_score,r.away_score
  from public.champions_league_predictions p
  join public.champions_league_fixtures f on f.id=p.fixture_id
  join public.players pl on pl.name=p.player_name and coalesce(pl.is_active,true)
  left join public.champions_league_results r on r.fixture_id=f.id
  where f.season=p_season and f.week=p_week
  order by p.player_name collate "tr-TR-x-icu",f.kickoff,f.id;
end
$$;

revoke execute on function public.get_champions_league_week(text,text,integer) from public, authenticated;
revoke execute on function public.save_champions_league_predictions(text,text,integer,jsonb) from public, authenticated;
revoke execute on function public.get_champions_league_ranking(text,text) from public, authenticated;
revoke execute on function public.get_champions_league_week_predictions(text,text,integer) from public, authenticated;

grant execute on function public.get_champions_league_week(text,text,integer) to anon;
grant execute on function public.save_champions_league_predictions(text,text,integer,jsonb) to anon;
grant execute on function public.get_champions_league_ranking(text,text) to anon;
grant execute on function public.get_champions_league_week_predictions(text,text,integer) to anon;
