create table if not exists public.game_share_clicks (
  id bigint generated by default as identity primary key,
  player_name text not null references public.players(name) on update cascade,
  channel text not null check (channel in ('whatsapp')),
  clicked_at timestamptz not null default now()
);

create index if not exists game_share_clicks_clicked_at_idx
  on public.game_share_clicks (clicked_at desc);
create index if not exists game_share_clicks_player_name_idx
  on public.game_share_clicks (player_name, clicked_at desc);

alter table public.game_share_clicks enable row level security;
revoke all on table public.game_share_clicks from anon, authenticated;
grant all on table public.game_share_clicks to service_role;

create or replace function public.record_game_share_click(
  p_token text,
  p_channel text default 'whatsapp'
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player text;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then
    raise exception 'Oturum geçersiz veya süresi dolmuş';
  end if;
  if p_channel <> 'whatsapp' then
    raise exception 'Paylaşım kanalı geçersiz';
  end if;
  insert into public.game_share_clicks(player_name,channel)
  values(v_player,p_channel);
  return true;
end
$$;

revoke execute on function public.record_game_share_click(text,text) from public, authenticated;
grant execute on function public.record_game_share_click(text,text) to anon;
