create table if not exists public.live_fixture_links (
  competition text not null check (competition in ('super_lig','champions_league')),
  fixture_id bigint not null,
  provider_fixture_id bigint not null unique,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (competition,fixture_id)
);

create table if not exists public.live_score_cache (
  competition text not null,
  fixture_id bigint not null,
  status text not null,
  elapsed smallint,
  home_score smallint check (home_score between 0 and 20),
  away_score smallint check (away_score between 0 and 20),
  fetched_at timestamptz not null,
  terminal_seen_count smallint not null default 0,
  terminal_signature text,
  primary key (competition,fixture_id),
  foreign key (competition,fixture_id) references public.live_fixture_links(competition,fixture_id) on delete cascade
);

create table if not exists public.live_score_daily_usage (
  usage_date date primary key,
  request_count integer not null default 0 check (request_count between 0 and 95),
  last_requested_at timestamptz
);

create table if not exists public.live_score_result_audit (
  id bigint generated by default as identity primary key,
  competition text not null check (competition in ('super_lig','champions_league')),
  fixture_id bigint not null,
  source text not null check (source in ('api_football','manual_override')),
  old_home_score smallint,
  old_away_score smallint,
  new_home_score smallint not null,
  new_away_score smallint not null,
  created_at timestamptz not null default now()
);

create index if not exists live_score_audit_fixture_idx on public.live_score_result_audit(competition,fixture_id,created_at desc);

alter table public.live_fixture_links enable row level security;
alter table public.live_score_cache enable row level security;
alter table public.live_score_daily_usage enable row level security;
alter table public.live_score_result_audit enable row level security;

revoke all on public.live_fixture_links from anon, authenticated;
revoke all on public.live_score_cache from anon, authenticated;
revoke all on public.live_score_daily_usage from anon, authenticated;
revoke all on public.live_score_result_audit from anon, authenticated;

create or replace function public.get_live_score_poll_gate(p_now timestamptz default now())
returns table(active_fixture_count integer,request_count integer,five_minutes_elapsed boolean)
language sql
security definer
set search_path=public,pg_temp
as $$
  with active as (
    select count(*)::integer n
    from public.live_fixture_links l
    where l.enabled and (
      (l.competition='super_lig' and exists(select 1 from public.fixtures f where f.id=l.fixture_id and p_now between f.kickoff-interval '10 minutes' and f.kickoff+interval '3 hours'))
      or
      (l.competition='champions_league' and exists(select 1 from public.champions_league_fixtures f where f.id=l.fixture_id and p_now between f.kickoff-interval '10 minutes' and f.kickoff+interval '3 hours'))
    ) and not exists(select 1 from public.live_score_cache c where c.competition=l.competition and c.fixture_id=l.fixture_id and c.terminal_seen_count>=2)
  ), usage as (
    select coalesce(u.request_count,0)::integer n,u.last_requested_at
    from (select 1) seed left join public.live_score_daily_usage u on u.usage_date=(p_now at time zone 'Europe/Istanbul')::date
  )
  select active.n,usage.n,(usage.last_requested_at is null or usage.last_requested_at<=p_now-interval '5 minutes') from active,usage;
$$;

create or replace function public.record_live_score_request(p_now timestamptz default now())
returns integer
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_count integer;
begin
  insert into public.live_score_daily_usage(usage_date,request_count,last_requested_at)
  values((p_now at time zone 'Europe/Istanbul')::date,1,p_now)
  on conflict(usage_date) do update set request_count=public.live_score_daily_usage.request_count+1,last_requested_at=excluded.last_requested_at
  where public.live_score_daily_usage.request_count<95
  returning request_count into v_count;
  if v_count is null then raise exception 'daily quota guard'; end if;
  return v_count;
end;
$$;

create or replace function public.record_provider_observation(
  p_competition text,p_fixture_id bigint,p_status text,p_elapsed smallint,
  p_home_score smallint,p_away_score smallint,p_fetched_at timestamptz default now()
)
returns table(terminal_seen_count smallint,terminal_signature text,should_finalize boolean)
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_terminal boolean:=p_status in ('FT','AET','PEN');
declare v_signature text:=case when p_status in ('FT','AET','PEN') then p_status||':'||p_home_score||':'||p_away_score end;
begin
  if p_competition not in ('super_lig','champions_league') or p_home_score not between 0 and 20 or p_away_score not between 0 and 20 then
    raise exception 'invalid live observation';
  end if;
  insert into public.live_score_cache(competition,fixture_id,status,elapsed,home_score,away_score,fetched_at,terminal_seen_count,terminal_signature)
  values(p_competition,p_fixture_id,p_status,p_elapsed,p_home_score,p_away_score,p_fetched_at,case when v_terminal then 1 else 0 end,v_signature)
  on conflict(competition,fixture_id) do update set
    status=excluded.status,elapsed=excluded.elapsed,home_score=excluded.home_score,away_score=excluded.away_score,fetched_at=excluded.fetched_at,
    terminal_seen_count=case when v_terminal and public.live_score_cache.terminal_signature=v_signature then public.live_score_cache.terminal_seen_count+1 when v_terminal then 1 else 0 end,
    terminal_signature=v_signature;
  return query select c.terminal_seen_count,c.terminal_signature,(c.terminal_seen_count>=2 and v_terminal) from public.live_score_cache c where c.competition=p_competition and c.fixture_id=p_fixture_id;
end;
$$;

create or replace function public.finalize_live_score_result(p_competition text,p_fixture_id bigint)
returns boolean
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare c public.live_score_cache%rowtype;
declare old_h smallint; declare old_a smallint;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_competition||':'||p_fixture_id,0));
  select * into c from public.live_score_cache where competition=p_competition and fixture_id=p_fixture_id for update;
  if not found or c.terminal_seen_count<2 or c.status not in ('FT','AET','PEN') then return false; end if;
  if exists(select 1 from public.live_score_result_audit a where a.competition=p_competition and a.fixture_id=p_fixture_id and a.source='manual_override') then return false; end if;
  if exists(select 1 from public.live_score_result_audit a where a.competition=p_competition and a.fixture_id=p_fixture_id and a.source='api_football' and a.new_home_score=c.home_score and a.new_away_score=c.away_score) then return false; end if;
  if p_competition='super_lig' then
    select home_score,away_score into old_h,old_a from public.results where fixture_id=p_fixture_id;
    insert into public.results(fixture_id,home_score,away_score,status,updated_at) values(p_fixture_id,c.home_score,c.away_score,'finished',now())
    on conflict(fixture_id) do update set home_score=excluded.home_score,away_score=excluded.away_score,status='finished',updated_at=now();
  elsif p_competition='champions_league' then
    select home_score,away_score into old_h,old_a from public.champions_league_results where fixture_id=p_fixture_id;
    insert into public.champions_league_results(fixture_id,home_score,away_score,updated_at) values(p_fixture_id,c.home_score,c.away_score,now())
    on conflict(fixture_id) do update set home_score=excluded.home_score,away_score=excluded.away_score,updated_at=now();
  else return false;
  end if;
  insert into public.live_score_result_audit(competition,fixture_id,source,old_home_score,old_away_score,new_home_score,new_away_score)
  values(p_competition,p_fixture_id,'api_football',old_h,old_a,c.home_score,c.away_score);
  return true;
end;
$$;

create or replace function public.get_today_live_match_cards(p_now timestamptz default now())
returns table(competition text,fixture_id bigint,status text,elapsed smallint,home_score smallint,away_score smallint,fetched_at timestamptz,exact_players text[])
language sql
security definer
set search_path=public,pg_temp
as $$
  with all_fixtures as (
    select 'super_lig'::text competition,f.id fixture_id,f.kickoff from public.fixtures f
    union all select 'champions_league',f.id,f.kickoff from public.champions_league_fixtures f
  )
  select af.competition,af.fixture_id,c.status,c.elapsed,c.home_score,c.away_score,c.fetched_at,
    case when p_now>=f.kickoff then coalesce((
      select array_agg(x.player_name order by x.player_name collate "tr-TR-x-icu") from (
        select p.player_name from public.predictions p join public.players pl on pl.name=p.player_name and pl.is_active=true
        where af.competition='super_lig' and p.fixture_id=af.fixture_id and p.home_score=c.home_score and p.away_score=c.away_score
        union all
        select p.player_name from public.champions_league_predictions p join public.players pl on pl.name=p.player_name and pl.is_active=true
        where af.competition='champions_league' and p.fixture_id=af.fixture_id and p.home_score=c.home_score and p.away_score=c.away_score
      ) x
    ),array[]::text[]) else array[]::text[] end
  from all_fixtures f join all_fixtures af on af.competition=f.competition and af.fixture_id=f.fixture_id
  join public.live_score_cache c on c.competition=af.competition and c.fixture_id=af.fixture_id
  where (f.kickoff at time zone 'Europe/Istanbul')::date=(p_now at time zone 'Europe/Istanbul')::date;
$$;

revoke all on function public.get_live_score_poll_gate(timestamptz) from public,anon,authenticated;
revoke all on function public.record_live_score_request(timestamptz) from public,anon,authenticated;
revoke all on function public.record_provider_observation(text,bigint,text,smallint,smallint,smallint,timestamptz) from public,anon,authenticated;
revoke all on function public.finalize_live_score_result(text,bigint) from public,anon,authenticated;
revoke all on function public.get_today_live_match_cards(timestamptz) from public,anon,authenticated;
grant execute on function public.get_today_live_match_cards(timestamptz) to anon,authenticated;
