create table if not exists public.player_invites (
  id bigint generated by default as identity primary key,
  inviter_name text not null references public.players(name) on update cascade,
  invited_name text not null references public.players(name) on update cascade,
  league_id uuid null references public.friend_leagues(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint player_invites_no_self check (lower(trim(inviter_name)) <> lower(trim(invited_name))),
  constraint player_invites_invited_once unique (invited_name)
);
create index if not exists player_invites_inviter_created_idx on public.player_invites(inviter_name,created_at desc);
alter table public.player_invites enable row level security;
revoke all on table public.player_invites from anon, authenticated;
grant all on table public.player_invites to service_role;

create or replace function public.record_player_invite(p_token text,p_inviter_name text,p_league_id uuid default null)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_invited text;begin
  v_invited:=public.friend_session_player(p_token);
  if v_invited is null then raise exception 'Oturum geçersiz veya süresi dolmuş';end if;
  if lower(trim(v_invited))=lower(trim(p_inviter_name)) then return false;end if;
  if not exists(select 1 from public.players where name=p_inviter_name and coalesce(is_active,true)=true) then return false;end if;
  insert into public.player_invites(inviter_name,invited_name,league_id) values(p_inviter_name,v_invited,p_league_id) on conflict(invited_name) do nothing;
  return found;
end $$;
revoke execute on function public.record_player_invite(text,text,uuid) from public,authenticated;
grant execute on function public.record_player_invite(text,text,uuid) to anon;

create or replace function public.get_invite_leaderboard(p_token text,p_period text default 'month')
returns table(player_name text,invite_count bigint,invite_rank bigint) language sql security definer set search_path='' as $$
  with viewer as (select public.friend_session_player(p_token) name), counts as (
    select i.inviter_name player_name,count(*) invite_count from public.player_invites i,viewer v
    where v.name is not null and (p_period='season' or i.created_at>=date_trunc('month',now())) group by i.inviter_name
  ) select player_name,invite_count,dense_rank() over(order by invite_count desc) invite_rank from counts order by invite_rank,player_name;
$$;
revoke execute on function public.get_invite_leaderboard(text,text) from public,authenticated;
grant execute on function public.get_invite_leaderboard(text,text) to anon;
