create table if not exists public.support_requests (
  id bigint generated by default as identity primary key,
  player_id bigint not null references public.players(id) on delete cascade,
  category text not null check (category in ('login_pin','predictions','points_ranking','technical','suggestion','other')),
  message text not null check (char_length(message) between 1 and 500),
  status text not null default 'new' check (status in ('new','answered','resolved')),
  admin_reply text check (admin_reply is null or char_length(admin_reply) between 1 and 1000),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  resolved_at timestamptz,
  player_seen_reply_at timestamptz
);

create table if not exists public.support_admins (
  player_id bigint primary key references public.players(id) on delete cascade,
  created_at timestamptz not null default now()
);

insert into public.support_admins(player_id)
select p.id
from public.players p
where lower(trim(p.name))='erdal' and coalesce(p.is_active,true)
on conflict(player_id) do nothing;

alter table public.support_requests enable row level security;
alter table public.support_admins enable row level security;
revoke all on public.support_requests from public, anon, authenticated;
revoke all on public.support_admins from public, anon, authenticated;
revoke all on sequence public.support_requests_id_seq from public, anon, authenticated;

create index if not exists support_requests_player_created_idx on public.support_requests(player_id,created_at desc);
create index if not exists support_requests_status_created_idx on public.support_requests(status,created_at desc);

create or replace function public.support_session_player_id(p_token text)
returns bigint
language sql
security definer
set search_path to ''
as $$
  select p.id
  from public.friend_league_sessions s
  join public.players p on p.name=s.player_name and coalesce(p.is_active,true)
  where s.token_hash=extensions.digest(coalesce(p_token,''),'sha256')
    and s.expires_at>now()
  limit 1
$$;

revoke all on function public.support_session_player_id(text) from public, anon, authenticated;

create or replace function public.is_support_admin(p_token text)
returns boolean
language sql
security definer
set search_path to ''
as $$
  select exists(
    select 1
    from public.support_admins a
    where a.player_id=public.support_session_player_id(p_token)
  )
$$;

create or replace function public.create_support_request(p_token text,p_category text,p_message text)
returns bigint
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_player_id bigint;
  v_category text;
  v_message text;
  v_id bigint;
begin
  v_player_id:=public.support_session_player_id(p_token);
  if v_player_id is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  v_category:=lower(trim(coalesce(p_category,'')));
  if v_category not in ('login_pin','predictions','points_ranking','technical','suggestion','other') then raise exception 'Destek kategorisi geçersiz'; end if;
  v_message:=trim(coalesce(p_message,''));
  if char_length(v_message)<1 or char_length(v_message)>500 then raise exception 'Mesaj 1-500 karakter arasında olmalıdır'; end if;
  insert into public.support_requests(player_id,category,message)
  values(v_player_id,v_category,v_message)
  returning id into v_id;
  return v_id;
end;
$$;

create or replace function public.list_my_support_requests(p_token text)
returns table(id bigint,category text,message text,status text,admin_reply text,created_at timestamptz,answered_at timestamptz,resolved_at timestamptz,player_seen_reply_at timestamptz)
language plpgsql
security definer
set search_path to ''
as $$
declare v_player_id bigint;
begin
  v_player_id:=public.support_session_player_id(p_token);
  if v_player_id is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  return query
  select r.id,r.category,r.message,r.status,r.admin_reply,r.created_at,r.answered_at,r.resolved_at,r.player_seen_reply_at
  from public.support_requests r
  where r.player_id=v_player_id
  order by r.created_at desc,r.id desc;
end;
$$;

create or replace function public.mark_support_reply_seen(p_token text,p_request_id bigint)
returns boolean
language plpgsql
security definer
set search_path to ''
as $$
declare v_player_id bigint;
begin
  v_player_id:=public.support_session_player_id(p_token);
  if v_player_id is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;
  update public.support_requests r
  set player_seen_reply_at=now()
  where r.id=p_request_id and r.player_id=v_player_id and r.admin_reply is not null;
  return found;
end;
$$;

create or replace function public.list_support_requests(p_admin_token text,p_status text default null)
returns table(id bigint,player_name text,category text,message text,status text,admin_reply text,created_at timestamptz,answered_at timestamptz,resolved_at timestamptz,player_seen_reply_at timestamptz)
language plpgsql
security definer
set search_path to ''
as $$
begin
  if not public.is_support_admin(p_admin_token) then raise exception 'Yetkisiz işlem'; end if;
  if p_status is not null and p_status not in ('new','answered','resolved') then raise exception 'Durum filtresi geçersiz'; end if;
  return query
  select r.id,p.name,r.category,r.message,r.status,r.admin_reply,r.created_at,r.answered_at,r.resolved_at,r.player_seen_reply_at
  from public.support_requests r
  join public.players p on p.id=r.player_id
  where p_status is null or r.status=p_status
  order by case when r.status='new' then 0 when r.status='answered' then 1 else 2 end,r.created_at desc,r.id desc;
end;
$$;

create or replace function public.reply_support_request(p_admin_token text,p_request_id bigint,p_reply text)
returns boolean
language plpgsql
security definer
set search_path to ''
as $$
declare v_reply text;
begin
  if not public.is_support_admin(p_admin_token) then raise exception 'Yetkisiz işlem'; end if;
  v_reply:=trim(coalesce(p_reply,''));
  if char_length(v_reply)<1 or char_length(v_reply)>1000 then raise exception 'Cevap 1-1000 karakter arasında olmalıdır'; end if;
  update public.support_requests
  set admin_reply=v_reply,status='answered',answered_at=now(),resolved_at=null,player_seen_reply_at=null
  where id=p_request_id;
  return found;
end;
$$;

create or replace function public.resolve_support_request(p_admin_token text,p_request_id bigint)
returns boolean
language plpgsql
security definer
set search_path to ''
as $$
begin
  if not public.is_support_admin(p_admin_token) then raise exception 'Yetkisiz işlem'; end if;
  update public.support_requests set status='resolved',resolved_at=now() where id=p_request_id;
  return found;
end;
$$;

revoke all on function public.is_support_admin(text) from public;
revoke all on function public.create_support_request(text,text,text) from public;
revoke all on function public.list_my_support_requests(text) from public;
revoke all on function public.mark_support_reply_seen(text,bigint) from public;
revoke all on function public.list_support_requests(text,text) from public;
revoke all on function public.reply_support_request(text,bigint,text) from public;
revoke all on function public.resolve_support_request(text,bigint) from public;

grant execute on function public.is_support_admin(text) to anon,authenticated;
grant execute on function public.create_support_request(text,text,text) to anon,authenticated;
grant execute on function public.list_my_support_requests(text) to anon,authenticated;
grant execute on function public.mark_support_reply_seen(text,bigint) to anon,authenticated;
grant execute on function public.list_support_requests(text,text) to anon,authenticated;
grant execute on function public.reply_support_request(text,bigint,text) to anon,authenticated;
grant execute on function public.resolve_support_request(text,bigint) to anon,authenticated;
