-- Bizim Skor Ligleri: izole veri modeli.
-- Bu migration mevcut Süper Lig / CL / Uluslar Ligi tablolarını değiştirmez.

create table if not exists public.league_periods (
  id bigint generated by default as identity primary key,
  period_no integer not null unique check (period_no > 0),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  status text not null default 'open' check (status in ('open','closed')),
  active_player_count integer not null default 0 check (active_player_count >= 0),
  locked_capacities jsonb not null default '{}'::jsonb,
  locked_promotion_slots jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  constraint league_period_dates_check check (ends_at > starts_at)
);

create table if not exists public.league_round_performance (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.league_periods(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  competition text not null check (competition in ('super_lig','champions_league','nations_league')),
  round_key text not null,
  participant_count integer not null check (participant_count >= 2),
  rank integer not null check (rank >= 1),
  performance_score numeric(6,2) not null check (performance_score >= 0 and performance_score <= 100),
  exact_score_count integer not null default 0 check (exact_score_count >= 0),
  raw_points bigint not null default 0 check (raw_points >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(period_id, player_id, competition, round_key),
  constraint league_round_rank_check check (rank <= participant_count)
);

create table if not exists public.league_memberships (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.league_periods(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  league_code text not null check (league_code in ('champions','elite','gold','silver','bronze')),
  starting_league_code text not null check (starting_league_code in ('champions','elite','gold','silver','bronze')),
  is_eligible boolean not null default false,
  valid_round_count integer not null default 0 check (valid_round_count >= 0),
  performance_score numeric(6,2),
  exact_score_count integer not null default 0 check (exact_score_count >= 0),
  raw_points bigint not null default 0 check (raw_points >= 0),
  rank_in_league integer,
  promotion_status text not null default 'none' check (promotion_status in ('none','promotion','relegation','championship')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(period_id, player_id),
  constraint league_membership_rank_check check (rank_in_league is null or rank_in_league >= 1),
  constraint league_membership_score_check check (performance_score is null or (performance_score >= 0 and performance_score <= 100))
);

create table if not exists public.league_history (
  id bigint generated by default as identity primary key,
  period_id bigint not null references public.league_periods(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  from_league text not null check (from_league in ('champions','elite','gold','silver','bronze')),
  to_league text not null check (to_league in ('champions','elite','gold','silver','bronze')),
  reason text not null check (reason in ('promotion','relegation','stay','initial')),
  final_rank integer,
  final_performance_score numeric(6,2),
  created_at timestamptz not null default now(),
  unique(period_id, player_id, from_league, to_league)
);

create index if not exists league_round_period_idx
  on public.league_round_performance(period_id, competition, round_key);
create index if not exists league_membership_period_league_idx
  on public.league_memberships(period_id, league_code, is_eligible);
create index if not exists league_history_player_idx
  on public.league_history(player_id, period_id desc);

create or replace function public.league_normalized_performance(
  p_rank integer,
  p_participant_count integer
) returns numeric
language sql
immutable
set search_path=''
as $$
  select case
    when p_rank is null
      or p_participant_count is null
      or p_participant_count < 2
      or p_rank < 1
      or p_rank > p_participant_count
      then null
    else round((100 * ((p_participant_count - p_rank)::numeric / (p_participant_count - 1)::numeric))::numeric, 2)
  end;
$$;

create or replace function public.league_allocate_capacities(
  p_active_count integer
) returns jsonb
language plpgsql
immutable
set search_path=''
as $$
declare
  v_count integer := greatest(coalesce(p_active_count,0),0);
  v_champions integer;
  v_elite integer;
  v_gold integer;
  v_silver integer;
  v_bronze integer;
begin
  if v_count = 0 then
    return jsonb_build_object(
      'champions',0,
      'elite',0,
      'gold',0,
      'silver',0,
      'bronze',0
    );
  end if;

  v_champions := round(v_count * 0.10);
  v_elite := round(v_count * 0.15);
  v_gold := round(v_count * 0.20);
  v_silver := round(v_count * 0.25);
  v_bronze := v_count - v_champions - v_elite - v_gold - v_silver;

  return jsonb_build_object(
    'champions',v_champions,
    'elite',v_elite,
    'gold',v_gold,
    'silver',v_silver,
    'bronze',v_bronze
  );
end;
$$;

create or replace function public.league_promotion_slots(
  p_capacities jsonb
) returns jsonb
language sql
immutable
set search_path=''
as $$
  select jsonb_build_object(
    'champions_elite', case when coalesce((p_capacities->>'champions')::integer,0) > 0 then greatest(1,round(((p_capacities->>'champions')::numeric) * 0.25)::integer) else 0 end,
    'elite_gold', case when coalesce((p_capacities->>'elite')::integer,0) > 0 then greatest(1,round(((p_capacities->>'elite')::numeric) * 0.33)::integer) else 0 end,
    'gold_silver', case when coalesce((p_capacities->>'gold')::integer,0) > 0 then greatest(1,round(((p_capacities->>'gold')::numeric) * 0.31)::integer) else 0 end,
    'silver_bronze', case when coalesce((p_capacities->>'silver')::integer,0) > 0 then greatest(1,round(((p_capacities->>'silver')::numeric) * 0.31)::integer) else 0 end
  );
$$;

create or replace function public.get_current_league_period()
returns table (
  id bigint,
  period_no integer,
  starts_at timestamptz,
  ends_at timestamptz,
  status text,
  active_player_count integer,
  locked_capacities jsonb,
  locked_promotion_slots jsonb
)
language sql
security definer
set search_path=''
as $$
  select
    p.id,
    p.period_no,
    p.starts_at,
    p.ends_at,
    p.status,
    p.active_player_count,
    p.locked_capacities,
    p.locked_promotion_slots
  from public.league_periods p
  where p.status='open'
  order by p.starts_at desc
  limit 1;
$$;

alter table public.league_periods enable row level security;
alter table public.league_round_performance enable row level security;
alter table public.league_memberships enable row level security;
alter table public.league_history enable row level security;

revoke all on public.league_periods from public,anon,authenticated;
revoke all on public.league_round_performance from public,anon,authenticated;
revoke all on public.league_memberships from public,anon,authenticated;
revoke all on public.league_history from public,anon,authenticated;
revoke execute on function public.league_allocate_capacities(integer) from public,anon,authenticated;
revoke execute on function public.league_promotion_slots(jsonb) from public,anon,authenticated;
revoke execute on function public.get_current_league_period() from public,authenticated;
grant execute on function public.get_current_league_period() to anon;
