create table public.pin_reset_attempts (
  id bigint generated by default as identity primary key,
  device_hash text not null,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

alter table public.pin_reset_attempts enable row level security;
create policy "PIN reset attempts are never directly accessible"
  on public.pin_reset_attempts
  for all
  to public
  using (false)
  with check (false);
revoke all on public.pin_reset_attempts from public;
revoke all on public.pin_reset_attempts from anon, authenticated;
revoke all on sequence public.pin_reset_attempts_id_seq from public, anon, authenticated;

create index pin_reset_attempts_device_time_idx
  on public.pin_reset_attempts(device_hash, attempted_at desc);

create or replace function public.reset_player_pin_from_registered_device(
  p_name text,
  p_device_id text,
  p_new_pin text
) returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_player public.players%rowtype;
  v_device_hash text;
  v_failed_count integer;
begin
  if p_device_id is null or length(p_device_id)<20 then return false; end if;
  if p_new_pin !~ '^[0-9]{4}$' then
    raise exception 'PIN yalnızca 4 rakamdan oluşmalıdır';
  end if;

  v_device_hash:=encode(digest(p_device_id,'sha256'),'hex');
  perform pg_advisory_xact_lock(hashtextextended(v_device_hash,0));

  delete from public.pin_reset_attempts
   where attempted_at<now()-interval '1 day';

  select count(*) into v_failed_count
    from public.pin_reset_attempts
   where device_hash=v_device_hash
     and not succeeded
     and attempted_at>now()-interval '15 minutes';

  if v_failed_count>=5 then
    raise exception 'Çok fazla deneme. 15 dakika sonra tekrar deneyin.';
  end if;

  select p.* into v_player
    from public.players p
   where p.is_active=true
     and lower(trim(regexp_replace(p.name,'\s+',' ','g')))=lower(trim(regexp_replace(p_name,'\s+',' ','g')))
     and p.device_id=p_device_id
   limit 1
   for update;

  if not found then
    insert into public.pin_reset_attempts(device_hash,succeeded)
    values(v_device_hash,false);
    return false;
  end if;

  update public.players
     set pin_hash=crypt(p_new_pin,gen_salt('bf')),
         force_pin_once=false
   where id=v_player.id;

  delete from public.friend_league_sessions
   where player_name=v_player.name;

  insert into public.pin_reset_attempts(device_hash,succeeded)
  values(v_device_hash,true);

  return true;
end;
$$;

revoke all on function public.reset_player_pin_from_registered_device(text,text,text) from public;
grant execute on function public.reset_player_pin_from_registered_device(text,text,text) to anon, authenticated;
