create table public.player_launch_events (
  id bigint generated by default as identity primary key,
  player_name text not null references public.players(name) on update cascade,
  device_id text not null check (char_length(device_id) between 1 and 200),
  launch_mode text not null check (launch_mode in ('home_screen','browser')),
  platform text not null check (char_length(platform) between 1 and 40),
  launched_at timestamptz not null default now()
);

create index player_launch_events_launched_at_idx
  on public.player_launch_events (launched_at desc);
create index player_launch_events_player_name_idx
  on public.player_launch_events (player_name, launched_at desc);

alter table public.player_launch_events enable row level security;
revoke all on table public.player_launch_events from anon, authenticated;
grant all on table public.player_launch_events to service_role;

create or replace function public.record_player_launch(
  p_token text,
  p_device_id text,
  p_launch_mode text,
  p_platform text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_player text;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then
    raise exception 'Oturum geçersiz veya süresi dolmuş';
  end if;
  if coalesce(trim(p_device_id),'')='' or char_length(p_device_id)>200 then
    raise exception 'Cihaz bilgisi geçersiz';
  end if;
  if p_launch_mode not in ('home_screen','browser') then
    raise exception 'Açılış türü geçersiz';
  end if;
  if coalesce(trim(p_platform),'')='' or char_length(p_platform)>40 then
    raise exception 'Platform bilgisi geçersiz';
  end if;

  insert into public.player_launch_events(player_name,device_id,launch_mode,platform)
  values(v_player,p_device_id,p_launch_mode,p_platform);
  return true;
end
$$;

revoke execute on function public.record_player_launch(text,text,text,text) from public, authenticated;
grant execute on function public.record_player_launch(text,text,text,text) to anon;
