create table public.game_announcements (
  id bigint generated by default as identity primary key,
  announcement_key text not null unique,
  title text not null,
  body text not null,
  image_path text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.game_announcement_acknowledgements (
  announcement_id bigint not null references public.game_announcements(id) on delete cascade,
  player_name text not null references public.players(name) on update cascade,
  acknowledged_at timestamptz not null default now(),
  primary key (announcement_id, player_name)
);

alter table public.game_announcements enable row level security;
alter table public.game_announcement_acknowledgements enable row level security;
revoke all on table public.game_announcements from anon, authenticated;
revoke all on table public.game_announcement_acknowledgements from anon, authenticated;
grant all on table public.game_announcements to service_role;
grant all on table public.game_announcement_acknowledgements to service_role;

insert into public.game_announcements(
  announcement_key,title,body,image_path,starts_at,ends_at
) values (
  'champions_prize_2026_5d',
  'Şampiyonlar Ligi Büyük Ödülü',
  'Sezon sonu Şampiyonlar Ligi sıralamasını 1. bitiren yarışmacıya bu futbol topu hediye!',
  'champions-prize-ball-v1.webp',
  now(),
  now() + interval '5 days'
);

create or replace function public.get_pending_game_announcement(p_token text)
returns table(
  announcement_key text,
  title text,
  body text,
  image_path text,
  ends_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare v_player text;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;

  return query
  select a.announcement_key,a.title,a.body,a.image_path,a.ends_at
  from public.game_announcements a
  where a.enabled
    and now() >= a.starts_at
    and now() < a.ends_at
    and not exists (
      select 1 from public.game_announcement_acknowledgements x
      where x.announcement_id=a.id and x.player_name=v_player
    )
  order by a.starts_at desc
  limit 1;
end
$$;

create or replace function public.acknowledge_game_announcement(
  p_token text,
  p_announcement_key text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_player text; v_announcement_id bigint;
begin
  v_player := public.friend_session_player(p_token);
  if v_player is null then raise exception 'Oturum geçersiz veya süresi dolmuş'; end if;

  select a.id into v_announcement_id
  from public.game_announcements a
  where a.announcement_key=p_announcement_key
    and a.enabled and now() >= a.starts_at and now() < a.ends_at;
  if v_announcement_id is null then return false; end if;

  insert into public.game_announcement_acknowledgements(announcement_id,player_name)
  values(v_announcement_id,v_player)
  on conflict (announcement_id, player_name) do nothing;
  return true;
end
$$;

revoke execute on function public.get_pending_game_announcement(text) from public, authenticated;
revoke execute on function public.acknowledge_game_announcement(text,text) from public, authenticated;
grant execute on function public.get_pending_game_announcement(text) to anon;
grant execute on function public.acknowledge_game_announcement(text,text) to anon;
