create table public.push_delivery_log (
  id bigint generated by default as identity primary key,
  delivery_key text not null unique,
  event_type text not null,
  player_name text not null,
  endpoint text not null,
  sent_at timestamptz not null default now(),
  response_status integer
);

alter table public.push_delivery_log enable row level security;
revoke all on table public.push_delivery_log from anon, authenticated;

select vault.create_secret(
  gen_random_uuid()::text,
  'notification_cron_secret',
  'Shared token used only by the notification pg_cron job'
);

create or replace function public.authorize_notification_cron(p_secret text)
returns boolean
language sql
security definer
set search_path = pg_catalog, public, vault
as $$
  select coalesce(
    p_secret = (
      select decrypted_secret from vault.decrypted_secrets
      where name = 'notification_cron_secret'
      order by created_at desc limit 1
    ), false
  );
$$;

revoke all on function public.authorize_notification_cron(text) from public, anon, authenticated;
grant execute on function public.authorize_notification_cron(text) to service_role;

do $$
declare existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job
  where jobname = 'notification-dispatch-every-five-minutes';
  if existing_job_id is not null then perform cron.unschedule(existing_job_id); end if;
end;
$$;

select cron.schedule(
  'notification-dispatch-every-five-minutes',
  '*/5 * * * *',
  $cron$
    select net.http_post(
      url := 'https://paevhzaixlozrrggnzni.supabase.co/functions/v1/notification-dispatch',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-secret', (
          select decrypted_secret from vault.decrypted_secrets
          where name = 'notification_cron_secret'
          order by created_at desc limit 1
        )
      ),
      body := '{}'::jsonb
    );
  $cron$
);